// ---------------------------------------------------------------------------
// Default pipelines — ship these as built-in discovery patterns
// ---------------------------------------------------------------------------

import type { PipelineDefinition } from "@shared/scanner-types";

export const DEFAULT_PIPELINES: PipelineDefinition[] = [
  {
    id: "volume_cluster",
    name: "Volume Cluster",
    enabled: true,
    category: "signal",
    trigger: {
      signalTypes: ["volume_spike"],
      subjectKind: "ticker",
      minMagnitude: 3.0,
    },
    lensIds: ["theme_membership", "peer_velocity", "sector_flow", "regime_context", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 10 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "weakness_cascade",
    name: "Weakness Cascade",
    enabled: true,
    category: "signal",
    trigger: {
      // broad_weakness only — per-theme breadth/accel go through theme_motion_scan
      // so a single theme move isn't killed by the multi-theme contagion gate.
      signalTypes: ["broad_weakness"],
      direction: "down",
    },
    lensIds: ["fastest_movers", "cross_theme", "regime_context", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 15 * 60_000,
    priority: "urgent",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "strength_surge",
    name: "Strength Surge",
    enabled: true,
    category: "signal",
    trigger: {
      signalTypes: ["broad_strength"],
      direction: "up",
    },
    lensIds: ["fastest_movers", "peer_velocity", "regime_context", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 10 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "theme_motion_scan",
    name: "Theme Motion",
    enabled: true,
    category: "signal",
    trigger: {
      signalTypes: ["breadth_shift", "theme_acceleration"],
      subjectKind: "theme",
    },
    lensIds: ["regime_context", "fastest_movers"],
    reactions: ["discovery_brief"],
    cooldownMs: 10 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "leadership_divergence",
    name: "Leadership Divergence",
    enabled: true,
    category: "signal",
    trigger: {
      signalTypes: ["velocity_move"],
      subjectKind: "ticker",
      minMagnitude: 2.0,
    },
    lensIds: ["theme_membership", "peer_velocity", "relative_strength"],
    reactions: ["discovery_brief"],
    cooldownMs: 30 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "gap_morning_scan",
    name: "Gap Morning Scan",
    enabled: true,
    category: "setup",
    trigger: {
      signalTypes: ["gap"],
      subjectKind: "ticker",
      minMagnitude: 3.0,
    },
    lensIds: ["theme_membership", "regime_context", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 4 * 60 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "regime_shift",
    name: "Regime Shift",
    enabled: true,
    category: "regime",
    trigger: {
      signalTypes: ["regime_change", "rai_shift"],
      subjectKind: "market",
    },
    lensIds: ["regime_context", "cross_theme", "fastest_movers"],
    reactions: ["discovery_brief"],
    cooldownMs: 30 * 60_000,
    priority: "urgent",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "adr_blowout_watch",
    name: "ADR Blowout Watch",
    enabled: true,
    category: "signal",
    trigger: {
      signalTypes: ["adr_blowout"],
      subjectKind: "ticker",
      minMagnitude: 2.5,
    },
    lensIds: ["theme_membership", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 60 * 60_000,
    priority: "low",
    ownerId: "system",
    visibility: "global",
  },

  // ── News Alert Pipeline ────────────────────────────────────────────────

  {
    id: "news_alert_scan",
    name: "News Alert",
    enabled: true,
    category: "alert",
    trigger: {
      signalTypes: ["news_alert"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context"],
    reactions: ["discovery_brief"],
    cooldownMs: 60 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },

  // ── Intraday Trade Setup Pipelines ──────────────────────────────────────

  {
    id: "lod_bounce_scan",
    name: "LOD Bounce",
    enabled: true,
    category: "setup",
    trigger: {
      signalTypes: ["lod_bounce"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 30 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "ma_reclaim_scan",
    name: "MA Reclaim (U&R)",
    enabled: true,
    category: "setup",
    trigger: {
      signalTypes: ["ur_ma_reclaim"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 60 * 60_000,
    // Default normal — urgent only when qualify upgrades (e.g. 200d + green day).
    // Hardcoding urgent made every 50d tick-reclaim on a dump day look like a fire drill.
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "ma_proximity_watch",
    name: "20d MA Proximity",
    enabled: true,
    category: "setup",
    trigger: {
      signalTypes: ["ma_proximity"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 30 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "prev_day_break_scan",
    name: "Prev Day Break",
    enabled: true,
    category: "setup",
    trigger: {
      signalTypes: ["prev_day_high_break", "prev_day_low_break"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 45 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "five_day_break_scan",
    name: "5-Day Break",
    enabled: true,
    category: "setup",
    trigger: {
      signalTypes: ["five_day_high_break", "five_day_low_break"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 45 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },

  // ── Earnings Pipelines ───────────────────────────────────────────────

  {
    id: "post_earnings_scan",
    name: "Post-Earnings Reaction",
    enabled: true,
    category: "earnings",
    trigger: {
      signalTypes: ["earnings_reaction"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context"],
    reactions: ["discovery_brief"],
    cooldownMs: 24 * 60 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "theme_earnings_density_scan",
    name: "Theme Earnings Density",
    enabled: true,
    category: "earnings",
    trigger: {
      signalTypes: ["theme_earnings_density"],
      subjectKind: "theme",
    },
    lensIds: ["regime_context"],
    reactions: ["discovery_brief"],
    cooldownMs: 24 * 60 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },

  // ── Short-Side Setup Pipelines ─────────────────────────────────────────

  {
    id: "failed_breakout_scan",
    name: "Failed Breakout",
    enabled: true,
    category: "setup",
    trigger: {
      signalTypes: ["failed_breakout"],
      subjectKind: "ticker",
      direction: "down",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 45 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "hod_fade_scan",
    name: "HOD Fade / Distribution",
    enabled: true,
    category: "setup",
    trigger: {
      signalTypes: ["hod_fade"],
      subjectKind: "ticker",
      direction: "down",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 60 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "gap_down_continuation_scan",
    name: "Gap Down Continuation",
    enabled: true,
    category: "setup",
    trigger: {
      signalTypes: ["gap_down_continuation"],
      subjectKind: "ticker",
      direction: "down",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 60 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },

  // ── IPO Debut Pipeline ──────────────────────────────────────────────────

  {
    id: "ipo_debut_scan",
    name: "IPO Debut",
    enabled: true,
    category: "alert",
    trigger: {
      signalTypes: ["ipo_debut"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context"],
    reactions: ["discovery_brief"],
    cooldownMs: 24 * 60 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
];
