// ---------------------------------------------------------------------------
// Default pipelines — ship these as built-in discovery patterns
// ---------------------------------------------------------------------------

import type { PipelineDefinition } from "@shared/scanner-types";

export const DEFAULT_PIPELINES: PipelineDefinition[] = [
  {
    id: "volume_cluster",
    name: "Volume Cluster",
    enabled: true,
    trigger: {
      signalTypes: ["volume_spike"],
      subjectKind: "ticker",
      minMagnitude: 3.0,
    },
    lensIds: ["theme_membership", "peer_velocity", "sector_flow", "regime_context", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 10 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "weakness_cascade",
    name: "Weakness Cascade",
    enabled: true,
    trigger: {
      signalTypes: ["breadth_shift", "broad_weakness"],
      direction: "down",
    },
    lensIds: ["fastest_movers", "cross_theme", "regime_context", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 15 * 60_000,
    priority: "urgent",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "strength_surge",
    name: "Strength Surge",
    enabled: true,
    trigger: {
      signalTypes: ["theme_acceleration", "broad_strength"],
      direction: "up",
    },
    lensIds: ["fastest_movers", "peer_velocity", "regime_context", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 10 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "leadership_divergence",
    name: "Leadership Divergence",
    enabled: true,
    trigger: {
      signalTypes: ["velocity_move"],
      subjectKind: "ticker",
      minMagnitude: 2.0,
    },
    lensIds: ["theme_membership", "peer_velocity", "relative_strength"],
    reactions: ["discovery_brief"],
    cooldownMs: 30 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "gap_morning_scan",
    name: "Gap Morning Scan",
    enabled: true,
    trigger: {
      signalTypes: ["gap"],
      subjectKind: "ticker",
      minMagnitude: 3.0,
    },
    lensIds: ["theme_membership", "regime_context", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 4 * 60 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "regime_shift",
    name: "Regime Shift",
    enabled: true,
    trigger: {
      signalTypes: ["regime_change", "rai_shift"],
      subjectKind: "market",
    },
    lensIds: ["regime_context", "cross_theme", "fastest_movers"],
    reactions: ["discovery_brief"],
    cooldownMs: 30 * 60_000,
    priority: "urgent",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "adr_blowout_watch",
    name: "ADR Blowout Watch",
    enabled: true,
    trigger: {
      signalTypes: ["adr_blowout"],
      subjectKind: "ticker",
      minMagnitude: 2.5,
    },
    lensIds: ["theme_membership", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 60 * 60_000,
    priority: "low",
    ownerId: "system",
    visibility: "global",
  },

  // ── News Alert Pipeline ────────────────────────────────────────────────

  {
    id: "news_alert_scan",
    name: "News Alert",
    enabled: true,
    trigger: {
      signalTypes: ["news_alert"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context"],
    reactions: ["discovery_brief"],
    cooldownMs: 60 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },

  // ── Intraday Trade Setup Pipelines ──────────────────────────────────────

  {
    id: "lod_bounce_scan",
    name: "LOD Bounce",
    enabled: true,
    trigger: {
      signalTypes: ["lod_bounce"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 30 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "ma_reclaim_scan",
    name: "MA Reclaim (U&R)",
    enabled: true,
    trigger: {
      signalTypes: ["ur_ma_reclaim"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 60 * 60_000,
    priority: "urgent",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "ma_proximity_watch",
    name: "20d MA Proximity",
    enabled: true,
    trigger: {
      signalTypes: ["ma_proximity"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 30 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "prev_day_break_scan",
    name: "Prev Day Break",
    enabled: true,
    trigger: {
      signalTypes: ["prev_day_high_break", "prev_day_low_break"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 45 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "five_day_break_scan",
    name: "5-Day Break",
    enabled: true,
    trigger: {
      signalTypes: ["five_day_high_break", "five_day_low_break"],
      subjectKind: "ticker",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 45 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },

  // ── Short-Side Setup Pipelines ─────────────────────────────────────────

  {
    id: "failed_breakout_scan",
    name: "Failed Breakout",
    enabled: true,
    trigger: {
      signalTypes: ["failed_breakout"],
      subjectKind: "ticker",
      direction: "down",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 45 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "hod_fade_scan",
    name: "HOD Fade / Distribution",
    enabled: true,
    trigger: {
      signalTypes: ["hod_fade"],
      subjectKind: "ticker",
      direction: "down",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure"],
    reactions: ["discovery_brief"],
    cooldownMs: 60 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
  {
    id: "gap_down_continuation_scan",
    name: "Gap Down Continuation",
    enabled: true,
    trigger: {
      signalTypes: ["gap_down_continuation"],
      subjectKind: "ticker",
      direction: "down",
    },
    lensIds: ["theme_membership", "regime_context", "ma_structure", "news"],
    reactions: ["discovery_brief"],
    cooldownMs: 60 * 60_000,
    priority: "normal",
    ownerId: "system",
    visibility: "global",
  },
];
