export function getUniverseTickers(universe: string): string[] {
  switch (universe) {
    case "dow30":
      return DOW30;
    case "nasdaq100":
      return NASDAQ100;
    case "sp500":
      return SP500;
    case "russell2000":
      return RUSSELL2000;
    default:
      return [];
  }
}

const DOW30: string[] = [
  "AAPL", "AMGN", "AXP", "BA", "CAT", "CRM", "CSCO", "CVX", "DIS", "DOW",
  "GS", "HD", "HON", "IBM", "INTC", "JNJ", "JPM", "KO", "MCD", "MMM",
  "MRK", "MSFT", "NKE", "PG", "TRV", "UNH", "V", "VZ", "WBA", "WMT",
];

const NASDAQ100: string[] = [
  "AAPL", "ABNB", "ADBE", "ADI", "ADP", "ADSK", "AEP", "AMAT", "AMGN", "AMZN",
  "ANSS", "APP", "ARM", "ASML", "AVGO", "AZN", "BIIB", "BKNG", "BKR", "CCEP",
  "CDNS", "CDW", "CEG", "CHTR", "CMCSA", "COST", "CPRT", "CRWD", "CSGP", "CSX",
  "CTAS", "CTSH", "DASH", "DDOG", "DLTR", "DXCM", "EA", "EXC", "FANG", "FAST",
  "FTNT", "GEHC", "GFS", "GILD", "GOOG", "GOOGL", "HON", "IDXX", "ILMN", "INTC",
  "INTU", "ISRG", "KDP", "KHC", "KLAC", "LIN", "LRCX", "LULU", "MAR", "MCHP",
  "MDB", "MDLZ", "MELI", "META", "MNST", "MRNA", "MRVL", "MSFT", "MU", "NFLX",
  "NVDA", "NXPI", "ODFL", "ON", "ORLY", "PANW", "PAYX", "PCAR", "PDD", "PEP",
  "PYPL", "QCOM", "REGN", "ROP", "ROST", "SBUX", "SMCI", "SNPS", "TEAM", "TMUS",
  "TRGP", "TSLA", "TTD", "TTWO", "TXN", "VRSK", "VRTX", "WBD", "WDAY", "XEL",
  "ZS",
];

const SP500: string[] = [
  "A", "AAPL", "ABBV", "ABNB", "ABT", "ACGL", "ACN", "ADBE", "ADI", "ADM",
  "ADP", "ADSK", "ADT", "AEE", "AEP", "AES", "AFL", "AIG", "AIZ", "AJG",
  "AKAM", "ALB", "ALGN", "ALL", "ALLE", "AMAT", "AMCR", "AMD", "AME", "AMGN",
  "AMP", "AMT", "AMZN", "ANET", "AON", "AOS", "APA", "APD", "APH", "APO",
  "APP", "APTV", "ARE", "ARES", "ATO", "AVB", "AVGO", "AVY", "AWK", "AXON",
  "AXP", "AZO", "BA", "BAC", "BALL", "BAX", "BBY", "BDX", "BEN", "BF.B",
  "BG", "BIIB", "BK", "BKNG", "BKR", "BLDR", "BLK", "BMY", "BP", "BR",
  "BRK.B", "BRO", "BSX", "BX", "BXP", "C", "CAG", "CAH", "CARR", "CAT",
  "CB", "CBOE", "CBRE", "CCI", "CCL", "CDNS", "CDW", "CEG", "CF", "CFG",
  "CHD", "CHRW", "CHTR", "CI", "CIEN", "CINF", "CL", "CLX", "CMCSA", "CME",
  "CMG", "CMI", "CMS", "CNC", "CNP", "COF", "COIN", "COO", "COP", "COR",
  "COST", "CPAY", "CPB", "CPRT", "CPT", "CRH", "CRL", "CRM", "CRWD", "CSCO",
  "CSGP", "CSX", "CTAS", "CTRA", "CTSH", "CTVA", "CVNA", "CVS", "CVX", "D",
  "DAL", "DASH", "DD", "DDOG", "DE", "DECK", "DELL", "DG", "DGX", "DHI",
  "DHR", "DIS", "DLR", "DLTR", "DOC", "DOV", "DOW", "DPZ", "DRI", "DTE",
  "DUK", "DVA", "DVN", "DXCM", "EA", "EBAY", "ECL", "ED", "EFX", "EG",
  "EIX", "EL", "ELV", "EME", "EMR", "EOG", "EPAM", "EQIX", "EQR", "EQT",
  "ERIE", "ES", "ESS", "ETN", "ETR", "EVRG", "EW", "EXC", "EXE", "EXPD",
  "EXPE", "EXR", "F", "FANG", "FAST", "FCX", "FDS", "FDX", "FE", "FFIV",
  "FICO", "FIS", "FISV", "FITB", "FIX", "FOX", "FOXA", "FRT", "FSLR", "FTNT",
  "FTV", "GD", "GDDY", "GE", "GEHC", "GEN", "GEV", "GILD", "GIS", "GL",
  "GLW", "GM", "GNRC", "GOOG", "GOOGL", "GPC", "GPN", "GRMN", "GS", "GWW",
  "HAL", "HAS", "HBAN", "HCA", "HD", "HIG", "HII", "HLT", "HOLX", "HON",
  "HOOD", "HPE", "HPQ", "HRL", "HSIC", "HST", "HSY", "HUBB", "HUM", "HWM",
  "IBKR", "IBM", "ICE", "IDXX", "IEX", "IFF", "INCY", "INTC", "INTU", "INVH",
  "IP", "IQV", "IR", "IRM", "ISRG", "IT", "ITT", "ITW", "IVZ", "J",
  "JBHT", "JBL", "JCI", "JKHY", "JNJ", "JPM", "KDP", "KEY", "KEYS", "KHC",
  "KIM", "KKR", "KLAC", "KMB", "KMI", "KO", "KR", "KVUE", "L", "LDOS",
  "LEN", "LH", "LHX", "LII", "LIN", "LLY", "LMT", "LNT", "LOW", "LRCX",
  "LULU", "LUV", "LVS", "LW", "LYB", "LYV", "MA", "MAA", "MAR", "MAS",
  "MCD", "MCHP", "MCK", "MCO", "MDLZ", "MDT", "MET", "META", "MGM", "MKC",
  "MLM", "MMM", "MNST", "MO", "MOH", "MOS", "MPC", "MPWR", "MRK", "MRNA",
  "MS", "MSCI", "MSFT", "MSI", "MTB", "MTCH", "MTD", "MU", "NCLH", "NDAQ",
  "NDSN", "NEE", "NEM", "NFLX", "NI", "NKE", "NOC", "NOW", "NRG", "NSC",
  "NTAP", "NTRS", "NUE", "NVDA", "NVR", "NWS", "NWSA", "NXPI", "O", "ODFL",
  "OKE", "OMC", "ON", "ORCL", "ORLY", "OTIS", "OXY", "PANW", "PAYC", "PAYX",
  "PCAR", "PCG", "PEG", "PEP", "PFE", "PFG", "PG", "PGR", "PH", "PHM",
  "PKG", "PLD", "PLTR", "PM", "PNC", "PNR", "PNW", "PODD", "POOL", "PPG",
  "PPL", "PRU", "PSA", "PSX", "PTC", "PVH", "PWR", "PYPL", "QCOM", "RCL",
  "REG", "REGN", "RF", "RJF", "RL", "RMD", "ROK", "ROL", "ROP", "ROST",
  "RSG", "RTX", "RVTY", "SAIC", "SBAC", "SBUX", "SCHW", "SHW", "SJM", "SLB",
  "SMCI", "SNA", "SNPS", "SO", "SOLV", "SPG", "SPGI", "SRE", "STE", "STLD",
  "STT", "STX", "STZ", "SW", "SWK", "SWKS", "SYF", "SYK", "SYY", "T",
  "TAP", "TDG", "TDY", "TECH", "TEL", "TER", "TFC", "TGT", "TJX", "TKO",
  "TMO", "TMUS", "TPL", "TPR", "TRGP", "TRMB", "TROW", "TRV", "TSCO", "TSLA",
  "TSN", "TT", "TTD", "TTWO", "TXN", "TXT", "TYL", "UAL", "UBER", "UDR",
  "UHS", "ULTA", "UNH", "UNP", "UPS", "URI", "USB", "V", "VICI", "VLO",
  "VLTO", "VMC", "VRSK", "VRSN", "VRTX", "VST", "VTR", "VTRS", "VZ", "WAB",
  "WAT", "WBD", "WDAY", "WDC", "WEC", "WELL", "WFC", "WM", "WMB", "WMT",
  "WRB", "WSM", "WST", "WTW", "WY", "WYNN", "XEL", "XOM", "XYL", "YUM",
  "ZBH", "ZBRA", "ZTS",
];

const RUSSELL2000: string[] = [
  "AAC", "AAMC", "AAOI", "AAON", "AAT", "AAWW", "ABAX", "ABCB", "ABCO", "ABEO",
  "ABG", "ABM", "ABMD", "ACAD", "ACCO", "ACET", "ACIW", "ACLS", "ACOR", "ACRE",
  "ACTG", "ADC", "ADMS", "ADTN", "ADUS", "AE", "AEIS", "AEL", "AEO", "AERI",
  "AFAM", "AGM", "AGX", "AGYS", "AHH", "AHS", "AHT", "AI", "AIMC", "AIN",
  "AIR", "AIT", "AJRD", "AKBA", "AKR", "AKS", "ALCO", "ALE", "ALEX", "ALG",
  "ALGT", "ALJ", "ALX", "AMAG", "AMBA", "AMBC", "AMC", "AMED", "AMKR", "AMNB",
  "AMOT", "AMPH", "AMRC", "AMSF", "AMSWA", "AMWD", "ANCX", "ANDE", "ANF", "ANGO",
  "ANH", "ANIK", "ANIP", "AOSL", "APEI", "APOG", "APPS", "APTS", "ARAY", "ARCB",
  "ARDX", "ARI", "AROW", "ARR", "ARTNA", "ARWR", "ASGN", "ASTE", "ATEN", "ATLO",
  "ATNI", "ATRA", "ATRC", "ATRI", "ATRO", "ATRS", "ATSG", "AVA", "AVAV", "AVD",
  "AVID", "AWR", "AXL", "AZPN", "AZZ", "B", "BANC", "BANF", "BANR", "BBSI",
  "BCC", "BCEI", "BCO", "BCOR", "BCOV", "BCPC", "BCRX", "BDC", "BHE", "BHLB",
  "BIG", "BJRI", "BKE", "BKH", "BLBD", "BLDR", "BLKB", "BLMN", "BMI", "BMRC",
  "BMTC", "BOOT", "BOX", "BRC", "BRKL", "BRKS", "BSET", "BTU", "BURL", "BUSE",
  "BXS", "BYD", "BZH", "CAC", "CACI", "CAKE", "CALM", "CALX", "CAMP", "CARA",
  "CASH", "CASS", "CASY", "CATO", "CATY", "CBB", "CBM", "CBRL", "CBU", "CBZ",
  "CCBG", "CCMP", "CCNE", "CCOI", "CCRN", "CCS", "CDE", "CECE", "CENTA", "CENX",
  "CERS", "CEVA", "CFFN", "CFI", "CHCO", "CHDN", "CHE", "CHEF", "CHFC", "CHGG",
  "CHS", "CHSP", "CHUY", "CIEN", "CIR", "CLF", "CLFD", "CLNE", "CLW", "CMC",
  "CMCO", "CMN", "CMO", "CMPR", "CMTL", "CNMD", "CNO", "CNS", "CNSL", "COBZ",
  "COHR", "COHU", "COKE", "COLB", "COLM", "CONN", "CORE", "CORT", "CPE", "CPF",
  "CPK", "CPSI", "CRAI", "CRMT", "CROX", "CRS", "CRUS", "CRVL", "CRY", "CSGS",
  "CSII", "CSS", "CSU", "CSV", "CTB", "CTBI", "CTO", "CTRE", "CTRN", "CTS",
  "CTWS", "CUBE", "CUBI", "CUTR", "CUZ", "CVBF", "CVCO", "CVG", "CVGW", "CVLT",
  "CVTI", "CW", "CWST", "CWT", "CYTK", "CZNC", "DAKT", "DAR", "DBD", "DCO",
  "DCOM", "DECK", "DENN", "DF", "DGII", "DIN", "DIOD", "DJCO", "DK", "DLX",
  "DMRC", "DOOR", "DORM", "DRH", "DSPG", "DX", "DXPE", "DY", "EAT", "EBIX",
  "EBS", "ECHO", "EE", "EEFT", "EFSC", "EGBN", "EGHT", "EGOV", "EGP", "EHTH",
  "EIG", "ELY", "EME", "ENPH", "ENS", "ENSG", "ENTA", "ENTG", "ENV", "ENVA",
  "EPAM", "EPAY", "EPM", "EPR", "ERA", "ERI", "ESCA", "ESE", "ESGR", "ESNT",
  "ETSY", "EVR", "EVTC", "EXAS", "EXEL", "EXLS", "EXPO", "EXTR", "FAF", "FARM",
  "FARO", "FBIZ", "FBNC", "FBP", "FCBC", "FCEL", "FCFS", "FCN", "FCNCA", "FDEF",
  "FDP", "FELE", "FET", "FFBC", "FFIN", "FIBK", "FICO", "FIVE", "FIVN", "FIX",
  "FIZZ", "FLIC", "FLWS", "FMBI", "FN", "FNB", "FNLC", "FOE", "FOLD", "FORM",
  "FORR", "FOXF", "FRAN", "FRGI", "FRME", "FRP", "FRPT", "FSS", "FUL", "FULT",
  "FWRD", "GABC", "GBCI", "GBL", "GBX", "GCAP", "GCO", "GDOT", "GEF", "GEO",
  "GES", "GFF", "GIII", "GLDD", "GLOB", "GLT", "GMED", "GNRC", "GOOD", "GPI",
  "GPT", "GRBK", "GRC", "GSM", "GTLS", "GTN", "GTY", "GVA", "GWRE", "HA",
  "HAE", "HAFC", "HALO", "HASI", "HAYN", "HBIO", "HBNC", "HCI", "HCSG", "HEES",
  "HEI", "HELE", "HF", "HFWA", "HHC", "HIBB", "HIFS", "HIW", "HL", "HLIT",
  "HLX", "HMN", "HNI", "HOMB", "HP", "HQY", "HRI", "HUBG", "HUBS", "HURC",
  "HURN", "HVT", "HWKN", "HZO", "IART", "IBCP", "IBKC", "IBOC", "IBP", "IBTX",
  "ICFI", "ICUI", "IDA", "IDCC", "IDT", "IIVI", "IMAX", "IMGN", "IMKTA", "INDB",
  "INFN", "INGN", "INN", "INO", "INSM", "IOSP", "IPAR", "IPHI", "IRBT", "IRDM",
  "IRET", "IRMD", "IRT", "IRWD", "ISBC", "ITCI", "ITRI", "IVR", "JACK", "JBSS",
  "JBT", "JCOM", "JJSF", "JOE", "JOUT", "JRVR", "KAI", "KALU", "KAMN", "KBH",
  "KELYA", "KEYW", "KFRC", "KFY", "KIRK", "KLXI", "KMPR", "KMT", "KNL", "KNX",
  "KTOS", "KVHI", "KW", "KWR", "LAD", "LADR", "LANC", "LBAI", "LCI", "LFUS",
  "LGIH", "LGND", "LHCG", "LHO", "LION", "LJPC", "LKFN", "LL", "LLNW", "LMAT",
  "LMNR", "LMNX", "LNCE", "LNN", "LOCO", "LOPE", "LPG", "LPSN", "LPX", "LRN",
  "LSCC", "LTC", "LXP", "MANH", "MANT", "MASI", "MATW", "MATX", "MBFI", "MBI",
  "MBUU", "MBVT", "MBWM", "MC", "MCF", "MCRI", "MCS", "MDC", "MDP", "MDR",
  "MED", "MEI", "MGEE", "MGI", "MGLN", "MGNX", "MGPI", "MHO", "MINI", "MITT",
  "MKSI", "MKTX", "MLAB", "MLHR", "MLI", "MLR", "MMI", "MMS", "MMSI", "MNKD",
  "MNR", "MNRO", "MOD", "MOH", "MOV", "MPAA", "MPW", "MPWR", "MRC", "MRCY",
  "MRTN", "MSA", "MSEX", "MSFG", "MSTR", "MTDR", "MTG", "MTH", "MTN", "MTRN",
  "MTRX", "MTSC", "MTSI", "MTX", "MTZ", "MWA", "MXL", "MYE", "MYGN", "MYRG",
  "NANO", "NAT", "NATR", "NAVG", "NBHC", "NBIX", "NBTB", "NCMI", "NDLS", "NEOG",
  "NHC", "NHI", "NJR", "NKTR", "NLS", "NMIH", "NNBR", "NNI", "NOG", "NPO",
  "NR", "NRZ", "NSA", "NSIT", "NSP", "NTCT", "NTGR", "NUVA", "NVAX", "NVEC",
  "NWBI", "NWE", "NWLI", "NWN", "NX", "NXRT", "NXST", "NYMT", "NYT", "OAS",
  "OCFC", "ODC", "OFG", "OFIX", "OGS", "OLED", "OLN", "OMCL", "OMI", "ONB",
  "OPB", "ORA", "ORC", "ORIT", "ORN", "OSBC", "OSIS", "OSTK", "OSUR", "OTTR",
  "OXM", "OZRK", "PACB", "PAHC", "PARR", "PATK", "PAYC", "PB", "PBH", "PCH",
  "PCRX", "PCTY", "PDCE", "PDFS", "PE", "PEB", "PEBO", "PEGA", "PEI", "PENN",
  "PETS", "PFBC", "PFIS", "PFPT", "PFS", "PFSI", "PFSW", "PGC", "PGTI", "PHX",
  "PIR", "PKE", "PKOH", "PLAY", "PLCE", "PLOW", "PLPC", "PLT", "PLUG", "PLXS",
  "PMT", "PNFP", "PNM", "PODD", "POOL", "POR", "POST", "POWI", "POWL", "PPBI",
  "PRAA", "PRFT", "PRGS", "PRI", "PRIM", "PRK", "PRO", "PRSC", "PSB", "PSMT",
  "PTCT", "PVTB", "PZZA", "QCRH", "QDEL", "QLYS", "QNST", "QTS", "QTWO", "QUAD",
  "RAIL", "RARE", "RBCAA", "RCII", "RDN", "RECN", "REGI", "REI", "REXR", "RGEN",
  "RGR", "RGS", "RH", "RHP", "RIGL", "RLI", "RLJ", "RMBS", "RNG", "RNST",
  "ROCK", "ROG", "ROIC", "ROLL", "RP", "RPT", "RRGB", "RSE", "RTEC", "RTIX",
  "RUBI", "RUTH", "RVNC", "RWT", "RXN", "RYAM", "SAFM", "SAFT", "SAGE", "SAH",
  "SAIA", "SAIC", "SAM", "SANM", "SASR", "SB", "SBCF", "SBGI", "SBRA", "SBSI",
  "SCHL", "SCHN", "SCL", "SCS", "SCVL", "SEAS", "SEM", "SF", "SFBS", "SFLY",
  "SFNC", "SFS", "SGC", "SGMO", "SGMS", "SGNT", "SHAK", "SHEN", "SHLM", "SHO",
  "SHOO", "SIGI", "SJI", "SJW", "SKYW", "SLAB", "SLCA", "SMCI", "SMP", "SMTC",
  "SN", "SNBC", "SNC", "SNCR", "SNX", "SONC", "SP", "SPKE", "SPNS", "SPOK",
  "SPSC", "SQBG", "SRCE", "SRDX", "SRI", "SRNE", "SRPT", "SSB", "SSD", "SSP",
  "SSTK", "SSYS", "STAA", "STAG", "STAR", "STBA", "STC", "STE", "STFC", "STL",
  "STMP", "STOR", "STRA", "STRT", "SUI", "SUP", "SUPN", "SWC", "SWM", "SWX",
  "SXC", "SXI", "SXT", "SYBT", "SYKE", "SYNA", "SYNT", "TBBK", "TBI", "TBK",
  "TBNK", "TCBI", "TCBK", "TCS", "TECD", "TEN", "TG", "TGH", "TGTX", "THFF",
  "THR", "THRM", "THS", "TILE", "TIPT", "TISI", "TITN", "TIVO", "TLN", "TLYS",
  "TMHC", "TMST", "TNC", "TNDM", "TNET", "TNK", "TOWN", "TPC", "TPH", "TR",
  "TREE", "TREX", "TRMK", "TRNO", "TROX", "TRS", "TRST", "TRUP", "TSC", "TSE",
  "TTEC", "TTEK", "TTGT", "TTI", "TTMI", "TTOO", "TTS", "TUBE", "TXMD", "TXRH",
  "TYL", "UAM", "UBNT", "UBSH", "UBSI", "UCBI", "UCTT", "UE", "UEIC", "UFCS",
  "UFI", "UFPI", "UHT", "UIS", "UMBF", "UMH", "UMPQ", "UNF", "UNFI", "UNT",
  "USAK", "USCR", "USNA", "USPH", "UTL", "UTMD", "UVE", "UVSP", "UVV", "VAC",
  "VCRA", "VCYT", "VECO", "VGR", "VHI", "VICR", "VIRT", "VLGEA", "VLY", "VNDA",
  "VOXX", "VPG", "VRA", "VRNS", "VRNT", "VRTV", "VSAT", "VSEC", "VSH", "VSTM",
  "VVI", "W", "WABC", "WAFD", "WAL", "WASH", "WBS", "WCG", "WDFC", "WERN",
  "WETF", "WEYS", "WGO", "WIBC", "WIFI", "WINA", "WIRE", "WIX", "WLH", "WMK",
  "WMS", "WNC", "WNR", "WOR", "WRE", "WRLD", "WSBC", "WSFS", "WSR", "WST",
  "WTBA", "WTFC", "WTI", "WTS", "WTW", "WWD", "WWE", "WWW", "XHR", "XNCR",
  "XOMA", "XPO", "YORW", "ZAGG", "ZEUS", "ZGNX", "ZIOP", "ZOES", "ZUMZ",
];
