export type SectorStock = { symbol: string; name: string; industry: string; marketCap: number };

export const STOCKS_BY_SECTOR: Record<string, SectorStock[]> = {
  'Technology': [
    { symbol: 'AAPL', name: 'Apple Inc.', industry: 'Consumer Electronics', marketCap: 3000e9 },
    { symbol: 'MSFT', name: 'Microsoft Corporation', industry: 'Software', marketCap: 2800e9 },
    { symbol: 'NVDA', name: 'NVIDIA Corporation', industry: 'Semiconductors', marketCap: 1200e9 },
    { symbol: 'GOOGL', name: 'Alphabet Inc.', industry: 'Internet Services', marketCap: 1800e9 },
    { symbol: 'META', name: 'Meta Platforms', industry: 'Internet Services', marketCap: 900e9 },
    { symbol: 'AVGO', name: 'Broadcom Inc.', industry: 'Semiconductors', marketCap: 350e9 },
    { symbol: 'ORCL', name: 'Oracle Corporation', industry: 'Software', marketCap: 320e9 },
    { symbol: 'CRM', name: 'Salesforce Inc.', industry: 'Software', marketCap: 250e9 },
    { symbol: 'AMD', name: 'Advanced Micro Devices', industry: 'Semiconductors', marketCap: 200e9 },
    { symbol: 'CSCO', name: 'Cisco Systems', industry: 'Networking', marketCap: 200e9 },
    { symbol: 'ADBE', name: 'Adobe Inc.', industry: 'Software', marketCap: 240e9 },
    { symbol: 'INTC', name: 'Intel Corporation', industry: 'Semiconductors', marketCap: 150e9 },
    { symbol: 'IBM', name: 'IBM', industry: 'IT Services', marketCap: 150e9 },
    { symbol: 'TXN', name: 'Texas Instruments', industry: 'Semiconductors', marketCap: 160e9 },
    { symbol: 'QCOM', name: 'Qualcomm Inc.', industry: 'Semiconductors', marketCap: 170e9 },
    { symbol: 'MU', name: 'Micron Technology', industry: 'Semiconductors', marketCap: 90e9 },
    { symbol: 'LRCX', name: 'Lam Research', industry: 'Semiconductor Equipment', marketCap: 100e9 },
  ],
  'Healthcare': [
    { symbol: 'UNH', name: 'UnitedHealth Group', industry: 'Health Insurance', marketCap: 500e9 },
    { symbol: 'JNJ', name: 'Johnson & Johnson', industry: 'Pharmaceuticals', marketCap: 400e9 },
    { symbol: 'LLY', name: 'Eli Lilly', industry: 'Pharmaceuticals', marketCap: 550e9 },
    { symbol: 'PFE', name: 'Pfizer Inc.', industry: 'Pharmaceuticals', marketCap: 160e9 },
    { symbol: 'ABBV', name: 'AbbVie Inc.', industry: 'Pharmaceuticals', marketCap: 280e9 },
    { symbol: 'MRK', name: 'Merck & Co.', industry: 'Pharmaceuticals', marketCap: 280e9 },
    { symbol: 'TMO', name: 'Thermo Fisher Scientific', industry: 'Life Sciences', marketCap: 210e9 },
    { symbol: 'ABT', name: 'Abbott Laboratories', industry: 'Medical Devices', marketCap: 190e9 },
    { symbol: 'DHR', name: 'Danaher Corporation', industry: 'Life Sciences', marketCap: 180e9 },
    { symbol: 'BMY', name: 'Bristol-Myers Squibb', industry: 'Pharmaceuticals', marketCap: 120e9 },
    { symbol: 'AMGN', name: 'Amgen Inc.', industry: 'Biotechnology', marketCap: 150e9 },
    { symbol: 'GILD', name: 'Gilead Sciences', industry: 'Biotechnology', marketCap: 100e9 },
    { symbol: 'MDT', name: 'Medtronic', industry: 'Medical Devices', marketCap: 110e9 },
    { symbol: 'BSX', name: 'Boston Scientific', industry: 'Medical Devices', marketCap: 90e9 },
    { symbol: 'BDX', name: 'Becton Dickinson', industry: 'Medical Devices', marketCap: 70e9 },
  ],
  'Financial Services': [
    { symbol: 'BRK.B', name: 'Berkshire Hathaway', industry: 'Diversified', marketCap: 800e9 },
    { symbol: 'JPM', name: 'JPMorgan Chase', industry: 'Banking', marketCap: 500e9 },
    { symbol: 'V', name: 'Visa Inc.', industry: 'Payment Processing', marketCap: 500e9 },
    { symbol: 'MA', name: 'Mastercard', industry: 'Payment Processing', marketCap: 400e9 },
    { symbol: 'BAC', name: 'Bank of America', industry: 'Banking', marketCap: 280e9 },
    { symbol: 'WFC', name: 'Wells Fargo', industry: 'Banking', marketCap: 180e9 },
    { symbol: 'GS', name: 'Goldman Sachs', industry: 'Investment Banking', marketCap: 140e9 },
    { symbol: 'MS', name: 'Morgan Stanley', industry: 'Investment Banking', marketCap: 150e9 },
    { symbol: 'SPGI', name: 'S&P Global', industry: 'Financial Data', marketCap: 130e9 },
    { symbol: 'BLK', name: 'BlackRock', industry: 'Asset Management', marketCap: 120e9 },
    { symbol: 'AXP', name: 'American Express', industry: 'Credit Services', marketCap: 170e9 },
    { symbol: 'C', name: 'Citigroup', industry: 'Banking', marketCap: 100e9 },
    { symbol: 'CME', name: 'CME Group', industry: 'Exchanges', marketCap: 80e9 },
    { symbol: 'ICE', name: 'Intercontinental Exchange', industry: 'Exchanges', marketCap: 70e9 },
    { symbol: 'PNC', name: 'PNC Financial', industry: 'Banking', marketCap: 65e9 },
    { symbol: 'USB', name: 'US Bancorp', industry: 'Banking', marketCap: 60e9 },
  ],
  'Consumer Cyclical': [
    { symbol: 'AMZN', name: 'Amazon.com', industry: 'E-Commerce', marketCap: 1500e9 },
    { symbol: 'TSLA', name: 'Tesla Inc.', industry: 'Auto Manufacturers', marketCap: 700e9 },
    { symbol: 'HD', name: 'Home Depot', industry: 'Home Improvement', marketCap: 350e9 },
    { symbol: 'MCD', name: "McDonald's", industry: 'Restaurants', marketCap: 210e9 },
    { symbol: 'NKE', name: 'Nike Inc.', industry: 'Footwear', marketCap: 140e9 },
    { symbol: 'SBUX', name: 'Starbucks', industry: 'Restaurants', marketCap: 110e9 },
    { symbol: 'LOW', name: "Lowe's", industry: 'Home Improvement', marketCap: 140e9 },
    { symbol: 'TJX', name: 'TJX Companies', industry: 'Retail', marketCap: 110e9 },
    { symbol: 'BKNG', name: 'Booking Holdings', industry: 'Travel', marketCap: 130e9 },
  ],
  'Consumer Defensive': [
    { symbol: 'WMT', name: 'Walmart Inc.', industry: 'Discount Stores', marketCap: 420e9 },
    { symbol: 'PG', name: 'Procter & Gamble', industry: 'Consumer Products', marketCap: 380e9 },
    { symbol: 'COST', name: 'Costco Wholesale', industry: 'Warehouse Clubs', marketCap: 300e9 },
    { symbol: 'KO', name: 'Coca-Cola', industry: 'Beverages', marketCap: 270e9 },
    { symbol: 'PEP', name: 'PepsiCo', industry: 'Beverages', marketCap: 240e9 },
    { symbol: 'PM', name: 'Philip Morris', industry: 'Tobacco', marketCap: 150e9 },
    { symbol: 'MO', name: 'Altria Group', industry: 'Tobacco', marketCap: 80e9 },
    { symbol: 'CL', name: 'Colgate-Palmolive', industry: 'Consumer Products', marketCap: 75e9 },
  ],
  'Energy': [
    { symbol: 'XOM', name: 'Exxon Mobil', industry: 'Oil & Gas', marketCap: 450e9 },
    { symbol: 'CVX', name: 'Chevron', industry: 'Oil & Gas', marketCap: 280e9 },
    { symbol: 'COP', name: 'ConocoPhillips', industry: 'Oil & Gas', marketCap: 130e9 },
    { symbol: 'EOG', name: 'EOG Resources', industry: 'Oil & Gas', marketCap: 70e9 },
  ],
  'Industrials': [
    { symbol: 'CAT', name: 'Caterpillar', industry: 'Heavy Machinery', marketCap: 170e9 },
    { symbol: 'RTX', name: 'RTX Corporation', industry: 'Aerospace & Defense', marketCap: 150e9 },
    { symbol: 'HON', name: 'Honeywell', industry: 'Aerospace & Defense', marketCap: 140e9 },
    { symbol: 'UNP', name: 'Union Pacific', industry: 'Railroads', marketCap: 150e9 },
    { symbol: 'BA', name: 'Boeing', industry: 'Aerospace & Defense', marketCap: 130e9 },
    { symbol: 'UPS', name: 'United Parcel Service', industry: 'Shipping', marketCap: 120e9 },
    { symbol: 'DE', name: 'Deere & Company', industry: 'Farm Machinery', marketCap: 120e9 },
    { symbol: 'LMT', name: 'Lockheed Martin', industry: 'Aerospace & Defense', marketCap: 120e9 },
    { symbol: 'GE', name: 'General Electric', industry: 'Aerospace & Defense', marketCap: 170e9 },
    { symbol: 'MMM', name: '3M Company', industry: 'Conglomerate', marketCap: 60e9 },
    { symbol: 'NSC', name: 'Norfolk Southern', industry: 'Railroads', marketCap: 55e9 },
    { symbol: 'NOC', name: 'Northrop Grumman', industry: 'Aerospace & Defense', marketCap: 75e9 },
    { symbol: 'GD', name: 'General Dynamics', industry: 'Aerospace & Defense', marketCap: 80e9 },
    { symbol: 'TDG', name: 'TransDigm Group', industry: 'Aerospace & Defense', marketCap: 65e9 },
    { symbol: 'HII', name: 'Huntington Ingalls', industry: 'Aerospace & Defense', marketCap: 12e9 },
    { symbol: 'LHX', name: 'L3Harris Technologies', industry: 'Aerospace & Defense', marketCap: 45e9 },
    { symbol: 'TXT', name: 'Textron Inc.', industry: 'Aerospace & Defense', marketCap: 18e9 },
  ],
  'Communication Services': [
    { symbol: 'GOOG', name: 'Alphabet Inc.', industry: 'Internet Services', marketCap: 1800e9 },
    { symbol: 'DIS', name: 'Walt Disney', industry: 'Entertainment', marketCap: 200e9 },
    { symbol: 'NFLX', name: 'Netflix', industry: 'Streaming', marketCap: 250e9 },
    { symbol: 'CMCSA', name: 'Comcast', industry: 'Cable', marketCap: 160e9 },
    { symbol: 'VZ', name: 'Verizon', industry: 'Telecom', marketCap: 170e9 },
    { symbol: 'T', name: 'AT&T', industry: 'Telecom', marketCap: 140e9 },
    { symbol: 'TMUS', name: 'T-Mobile', industry: 'Telecom', marketCap: 200e9 },
  ],
  'Utilities': [
    { symbol: 'NEE', name: 'NextEra Energy', industry: 'Utilities', marketCap: 150e9 },
    { symbol: 'DUK', name: 'Duke Energy', industry: 'Utilities', marketCap: 80e9 },
    { symbol: 'SO', name: 'Southern Company', industry: 'Utilities', marketCap: 85e9 },
  ],
  'Real Estate': [
    { symbol: 'AMT', name: 'American Tower', industry: 'REITs', marketCap: 100e9 },
    { symbol: 'PLD', name: 'Prologis', industry: 'REITs', marketCap: 110e9 },
    { symbol: 'EQIX', name: 'Equinix', industry: 'Data Centers', marketCap: 75e9 },
  ],
};

export function findSectorForSymbol(symbol: string): { sector: string; industry: string } | null {
  const upperSymbol = symbol.toUpperCase();
  for (const [sector, stocks] of Object.entries(STOCKS_BY_SECTOR)) {
    const stock = stocks.find(s => s.symbol === upperSymbol);
    if (stock) {
      return { sector, industry: stock.industry };
    }
  }
  return null;
}
