export type SectorStock = { symbol: string; name: string; industry: string; marketCap: number };

export const STOCKS_BY_SECTOR: Record<string, SectorStock[]> = {
  'Technology': [
    { symbol: 'AAPL', name: 'Apple Inc.', industry: 'Consumer Electronics', marketCap: 3000e9 },
    { symbol: 'MSFT', name: 'Microsoft Corporation', industry: 'Software', marketCap: 2800e9 },
    { symbol: 'NVDA', name: 'NVIDIA Corporation', industry: 'Semiconductors', marketCap: 1200e9 },
    { symbol: 'GOOGL', name: 'Alphabet Inc.', industry: 'Internet Services', marketCap: 1800e9 },
    { symbol: 'META', name: 'Meta Platforms', industry: 'Internet Services', marketCap: 900e9 },
    { symbol: 'AVGO', name: 'Broadcom Inc.', industry: 'Semiconductors', marketCap: 350e9 },
    { symbol: 'ORCL', name: 'Oracle Corporation', industry: 'Software', marketCap: 320e9 },
    { symbol: 'CRM', name: 'Salesforce Inc.', industry: 'Software', marketCap: 250e9 },
    { symbol: 'AMD', name: 'Advanced Micro Devices', industry: 'Semiconductors', marketCap: 200e9 },
    { symbol: 'CSCO', name: 'Cisco Systems', industry: 'Networking', marketCap: 200e9 },
    { symbol: 'ADBE', name: 'Adobe Inc.', industry: 'Software', marketCap: 240e9 },
    { symbol: 'INTC', name: 'Intel Corporation', industry: 'Semiconductors', marketCap: 150e9 },
    { symbol: 'IBM', name: 'IBM', industry: 'IT Services', marketCap: 150e9 },
    { symbol: 'TXN', name: 'Texas Instruments', industry: 'Semiconductors', marketCap: 160e9 },
    { symbol: 'QCOM', name: 'Qualcomm Inc.', industry: 'Semiconductors', marketCap: 170e9 },
    { symbol: 'MU', name: 'Micron Technology', industry: 'Semiconductors', marketCap: 90e9 },
    { symbol: 'LRCX', name: 'Lam Research', industry: 'Semiconductor Equipment', marketCap: 100e9 },
    { symbol: 'AMAT', name: 'Applied Materials', industry: 'Semiconductor Equipment', marketCap: 130e9 },
    { symbol: 'KLAC', name: 'KLA Corporation', industry: 'Semiconductor Equipment', marketCap: 75e9 },
    { symbol: 'ASML', name: 'ASML Holding', industry: 'Semiconductor Equipment', marketCap: 300e9 },
    { symbol: 'NOW', name: 'ServiceNow', industry: 'Software', marketCap: 150e9 },
    { symbol: 'PANW', name: 'Palo Alto Networks', industry: 'Software', marketCap: 100e9 },
    { symbol: 'SNPS', name: 'Synopsys', industry: 'Software', marketCap: 80e9 },
    { symbol: 'CDNS', name: 'Cadence Design Systems', industry: 'Software', marketCap: 75e9 },
    { symbol: 'FTNT', name: 'Fortinet', industry: 'Software', marketCap: 60e9 },
    { symbol: 'ACN', name: 'Accenture', industry: 'IT Services', marketCap: 220e9 },
    { symbol: 'CTSH', name: 'Cognizant Technology', industry: 'IT Services', marketCap: 40e9 },
    { symbol: 'INFY', name: 'Infosys', industry: 'IT Services', marketCap: 75e9 },
  ],
  'Healthcare': [
    { symbol: 'UNH', name: 'UnitedHealth Group', industry: 'Health Insurance', marketCap: 500e9 },
    { symbol: 'JNJ', name: 'Johnson & Johnson', industry: 'Pharmaceuticals', marketCap: 400e9 },
    { symbol: 'LLY', name: 'Eli Lilly', industry: 'Pharmaceuticals', marketCap: 550e9 },
    { symbol: 'PFE', name: 'Pfizer Inc.', industry: 'Pharmaceuticals', marketCap: 160e9 },
    { symbol: 'ABBV', name: 'AbbVie Inc.', industry: 'Pharmaceuticals', marketCap: 280e9 },
    { symbol: 'MRK', name: 'Merck & Co.', industry: 'Pharmaceuticals', marketCap: 280e9 },
    { symbol: 'TMO', name: 'Thermo Fisher Scientific', industry: 'Life Sciences', marketCap: 210e9 },
    { symbol: 'ABT', name: 'Abbott Laboratories', industry: 'Medical Devices', marketCap: 190e9 },
    { symbol: 'DHR', name: 'Danaher Corporation', industry: 'Life Sciences', marketCap: 180e9 },
    { symbol: 'BMY', name: 'Bristol-Myers Squibb', industry: 'Pharmaceuticals', marketCap: 120e9 },
    { symbol: 'AMGN', name: 'Amgen Inc.', industry: 'Biotechnology', marketCap: 150e9 },
    { symbol: 'GILD', name: 'Gilead Sciences', industry: 'Biotechnology', marketCap: 100e9 },
    { symbol: 'MDT', name: 'Medtronic', industry: 'Medical Devices', marketCap: 110e9 },
    { symbol: 'BSX', name: 'Boston Scientific', industry: 'Medical Devices', marketCap: 90e9 },
    { symbol: 'BDX', name: 'Becton Dickinson', industry: 'Medical Devices', marketCap: 70e9 },
    { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', industry: 'Biotechnology', marketCap: 110e9 },
    { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', industry: 'Biotechnology', marketCap: 100e9 },
    { symbol: 'BIIB', name: 'Biogen', industry: 'Biotechnology', marketCap: 35e9 },
    { symbol: 'HCA', name: 'HCA Healthcare', industry: 'Health Insurance', marketCap: 85e9 },
    { symbol: 'CI', name: 'Cigna Group', industry: 'Health Insurance', marketCap: 95e9 },
    { symbol: 'ELV', name: 'Elevance Health', industry: 'Health Insurance', marketCap: 110e9 },
    { symbol: 'HUM', name: 'Humana', industry: 'Health Insurance', marketCap: 45e9 },
    { symbol: 'CVS', name: 'CVS Health', industry: 'Health Insurance', marketCap: 90e9 },
    { symbol: 'ISRG', name: 'Intuitive Surgical', industry: 'Medical Devices', marketCap: 150e9 },
    { symbol: 'SYK', name: 'Stryker Corporation', industry: 'Medical Devices', marketCap: 120e9 },
    { symbol: 'ZBH', name: 'Zimmer Biomet', industry: 'Medical Devices', marketCap: 28e9 },
    { symbol: 'EW', name: 'Edwards Lifesciences', industry: 'Medical Devices', marketCap: 45e9 },
  ],
  'Financial Services': [
    { symbol: 'BRK.B', name: 'Berkshire Hathaway', industry: 'Diversified', marketCap: 800e9 },
    { symbol: 'JPM', name: 'JPMorgan Chase', industry: 'Banking', marketCap: 500e9 },
    { symbol: 'V', name: 'Visa Inc.', industry: 'Payment Processing', marketCap: 500e9 },
    { symbol: 'MA', name: 'Mastercard', industry: 'Payment Processing', marketCap: 400e9 },
    { symbol: 'BAC', name: 'Bank of America', industry: 'Banking', marketCap: 280e9 },
    { symbol: 'WFC', name: 'Wells Fargo', industry: 'Banking', marketCap: 180e9 },
    { symbol: 'GS', name: 'Goldman Sachs', industry: 'Investment Banking', marketCap: 140e9 },
    { symbol: 'MS', name: 'Morgan Stanley', industry: 'Investment Banking', marketCap: 150e9 },
    { symbol: 'SPGI', name: 'S&P Global', industry: 'Financial Data', marketCap: 130e9 },
    { symbol: 'BLK', name: 'BlackRock', industry: 'Asset Management', marketCap: 120e9 },
    { symbol: 'AXP', name: 'American Express', industry: 'Credit Services', marketCap: 170e9 },
    { symbol: 'C', name: 'Citigroup', industry: 'Banking', marketCap: 100e9 },
    { symbol: 'CME', name: 'CME Group', industry: 'Exchanges', marketCap: 80e9 },
    { symbol: 'ICE', name: 'Intercontinental Exchange', industry: 'Exchanges', marketCap: 70e9 },
    { symbol: 'PNC', name: 'PNC Financial', industry: 'Banking', marketCap: 65e9 },
    { symbol: 'USB', name: 'US Bancorp', industry: 'Banking', marketCap: 60e9 },
    { symbol: 'ALL', name: 'Allstate Corporation', industry: 'Insurance', marketCap: 45e9 },
    { symbol: 'TRV', name: 'Travelers Companies', industry: 'Insurance', marketCap: 50e9 },
    { symbol: 'PGR', name: 'Progressive Corporation', industry: 'Insurance', marketCap: 120e9 },
    { symbol: 'CB', name: 'Chubb Limited', industry: 'Insurance', marketCap: 100e9 },
    { symbol: 'SCHW', name: 'Charles Schwab', industry: 'Regional Banks', marketCap: 130e9 },
    { symbol: 'FITB', name: 'Fifth Third Bancorp', industry: 'Regional Banks', marketCap: 28e9 },
  ],
  'Consumer Cyclical': [
    { symbol: 'AMZN', name: 'Amazon.com', industry: 'E-Commerce', marketCap: 1500e9 },
    { symbol: 'TSLA', name: 'Tesla Inc.', industry: 'Auto Manufacturers', marketCap: 700e9 },
    { symbol: 'HD', name: 'Home Depot', industry: 'Home Improvement', marketCap: 350e9 },
    { symbol: 'MCD', name: "McDonald's", industry: 'Restaurants', marketCap: 210e9 },
    { symbol: 'NKE', name: 'Nike Inc.', industry: 'Footwear', marketCap: 140e9 },
    { symbol: 'SBUX', name: 'Starbucks', industry: 'Restaurants', marketCap: 110e9 },
    { symbol: 'LOW', name: "Lowe's", industry: 'Home Improvement', marketCap: 140e9 },
    { symbol: 'TJX', name: 'TJX Companies', industry: 'Retail', marketCap: 110e9 },
    { symbol: 'BKNG', name: 'Booking Holdings', industry: 'Travel', marketCap: 130e9 },
    { symbol: 'BLDR', name: 'Builders FirstSource', industry: 'Home Improvement', marketCap: 22e9 },
    { symbol: 'POOL', name: 'Pool Corporation', industry: 'Home Improvement', marketCap: 14e9 },
    { symbol: 'FND', name: 'Floor & Decor Holdings', industry: 'Home Improvement', marketCap: 10e9 },
    { symbol: 'WSM', name: 'Williams-Sonoma', industry: 'Home Improvement', marketCap: 18e9 },
    { symbol: 'RH', name: 'RH (Restoration Hardware)', industry: 'Home Improvement', marketCap: 7e9 },
    { symbol: 'BECN', name: 'Beacon Roofing Supply', industry: 'Home Improvement', marketCap: 6e9 },
    { symbol: 'SWK', name: 'Stanley Black & Decker', industry: 'Home Improvement', marketCap: 14e9 },
    { symbol: 'CMG', name: 'Chipotle Mexican Grill', industry: 'Restaurants', marketCap: 75e9 },
    { symbol: 'DPZ', name: "Domino's Pizza", industry: 'Restaurants', marketCap: 16e9 },
    { symbol: 'YUM', name: 'Yum! Brands', industry: 'Restaurants', marketCap: 40e9 },
    { symbol: 'DINE', name: 'Dine Brands Global', industry: 'Restaurants', marketCap: 1.5e9 },
    { symbol: 'QSR', name: 'Restaurant Brands International', industry: 'Restaurants', marketCap: 22e9 },
    { symbol: 'WING', name: 'Wingstop', industry: 'Restaurants', marketCap: 10e9 },
    { symbol: 'CAVA', name: 'CAVA Group', industry: 'Restaurants', marketCap: 12e9 },
    { symbol: 'TXRH', name: 'Texas Roadhouse', industry: 'Restaurants', marketCap: 12e9 },
    { symbol: 'DRI', name: 'Darden Restaurants', industry: 'Restaurants', marketCap: 20e9 },
    { symbol: 'SHOP', name: 'Shopify', industry: 'E-Commerce', marketCap: 95e9 },
    { symbol: 'ETSY', name: 'Etsy', industry: 'E-Commerce', marketCap: 8e9 },
    { symbol: 'EBAY', name: 'eBay', industry: 'E-Commerce', marketCap: 28e9 },
    { symbol: 'W', name: 'Wayfair', industry: 'E-Commerce', marketCap: 6e9 },
    { symbol: 'CHWY', name: 'Chewy', industry: 'E-Commerce', marketCap: 12e9 },
    { symbol: 'GM', name: 'General Motors', industry: 'Auto Manufacturers', marketCap: 50e9 },
    { symbol: 'F', name: 'Ford Motor Company', industry: 'Auto Manufacturers', marketCap: 45e9 },
    { symbol: 'RIVN', name: 'Rivian Automotive', industry: 'Auto Manufacturers', marketCap: 15e9 },
    { symbol: 'LCID', name: 'Lucid Group', industry: 'Auto Manufacturers', marketCap: 7e9 },
    { symbol: 'DECK', name: 'Deckers Outdoor', industry: 'Footwear', marketCap: 25e9 },
    { symbol: 'ON', name: 'On Holding', industry: 'Footwear', marketCap: 15e9 },
    { symbol: 'CROX', name: 'Crocs Inc.', industry: 'Footwear', marketCap: 8e9 },
    { symbol: 'SKX', name: 'Skechers USA', industry: 'Footwear', marketCap: 10e9 },
    { symbol: 'ROST', name: 'Ross Stores', industry: 'Retail', marketCap: 50e9 },
    { symbol: 'BBY', name: 'Best Buy', industry: 'Retail', marketCap: 18e9 },
    { symbol: 'DG', name: 'Dollar General', industry: 'Retail', marketCap: 25e9 },
    { symbol: 'DLTR', name: 'Dollar Tree', industry: 'Retail', marketCap: 28e9 },
    { symbol: 'FIVE', name: 'Five Below', industry: 'Retail', marketCap: 8e9 },
    { symbol: 'ULTA', name: 'Ulta Beauty', industry: 'Retail', marketCap: 22e9 },
    { symbol: 'EXPE', name: 'Expedia Group', industry: 'Travel', marketCap: 22e9 },
    { symbol: 'ABNB', name: 'Airbnb', industry: 'Travel', marketCap: 85e9 },
    { symbol: 'MAR', name: 'Marriott International', industry: 'Travel', marketCap: 70e9 },
    { symbol: 'HLT', name: 'Hilton Worldwide', industry: 'Travel', marketCap: 55e9 },
    { symbol: 'H', name: 'Hyatt Hotels', industry: 'Travel', marketCap: 15e9 },
    { symbol: 'TOL', name: 'Toll Brothers', industry: 'Homebuilders', marketCap: 12e9 },
    { symbol: 'DHI', name: 'D.R. Horton', industry: 'Homebuilders', marketCap: 45e9 },
    { symbol: 'LEN', name: 'Lennar Corporation', industry: 'Homebuilders', marketCap: 38e9 },
    { symbol: 'PHM', name: 'PulteGroup', industry: 'Homebuilders', marketCap: 22e9 },
    { symbol: 'KBH', name: 'KB Home', industry: 'Homebuilders', marketCap: 6e9 },
    { symbol: 'NVR', name: 'NVR Inc.', industry: 'Homebuilders', marketCap: 28e9 },
    { symbol: 'MTH', name: 'Meritage Homes', industry: 'Homebuilders', marketCap: 8e9 },
    { symbol: 'MDC', name: 'MDC Holdings', industry: 'Homebuilders', marketCap: 6e9 },
    { symbol: 'AZO', name: 'AutoZone', industry: 'Auto Parts', marketCap: 52e9 },
    { symbol: 'ORLY', name: "O'Reilly Automotive", industry: 'Auto Parts', marketCap: 60e9 },
    { symbol: 'AAP', name: 'Advance Auto Parts', industry: 'Auto Parts', marketCap: 4e9 },
    { symbol: 'GPC', name: 'Genuine Parts Company', industry: 'Auto Parts', marketCap: 20e9 },
  ],
  'Consumer Defensive': [
    { symbol: 'WMT', name: 'Walmart Inc.', industry: 'Discount Stores', marketCap: 420e9 },
    { symbol: 'PG', name: 'Procter & Gamble', industry: 'Consumer Products', marketCap: 380e9 },
    { symbol: 'COST', name: 'Costco Wholesale', industry: 'Warehouse Clubs', marketCap: 300e9 },
    { symbol: 'KO', name: 'Coca-Cola', industry: 'Beverages', marketCap: 270e9 },
    { symbol: 'PEP', name: 'PepsiCo', industry: 'Beverages', marketCap: 240e9 },
    { symbol: 'PM', name: 'Philip Morris', industry: 'Tobacco', marketCap: 150e9 },
    { symbol: 'MO', name: 'Altria Group', industry: 'Tobacco', marketCap: 80e9 },
    { symbol: 'CL', name: 'Colgate-Palmolive', industry: 'Consumer Products', marketCap: 75e9 },
    { symbol: 'KR', name: 'Kroger', industry: 'Grocery', marketCap: 40e9 },
    { symbol: 'SYY', name: 'Sysco Corporation', industry: 'Grocery', marketCap: 40e9 },
    { symbol: 'KMB', name: 'Kimberly-Clark', industry: 'Consumer Products', marketCap: 45e9 },
    { symbol: 'CHD', name: 'Church & Dwight', industry: 'Consumer Products', marketCap: 25e9 },
    { symbol: 'STZ', name: 'Constellation Brands', industry: 'Beverages', marketCap: 40e9 },
    { symbol: 'MNST', name: 'Monster Beverage', industry: 'Beverages', marketCap: 55e9 },
  ],
  'Energy': [
    { symbol: 'XOM', name: 'Exxon Mobil', industry: 'Oil & Gas', marketCap: 450e9 },
    { symbol: 'CVX', name: 'Chevron', industry: 'Oil & Gas', marketCap: 280e9 },
    { symbol: 'COP', name: 'ConocoPhillips', industry: 'Oil & Gas', marketCap: 130e9 },
    { symbol: 'EOG', name: 'EOG Resources', industry: 'Oil & Gas', marketCap: 70e9 },
    { symbol: 'SLB', name: 'Schlumberger', industry: 'Oil & Gas', marketCap: 65e9 },
    { symbol: 'HAL', name: 'Halliburton', industry: 'Oil & Gas', marketCap: 28e9 },
    { symbol: 'OXY', name: 'Occidental Petroleum', industry: 'Oil & Gas', marketCap: 50e9 },
    { symbol: 'DVN', name: 'Devon Energy', industry: 'Oil & Gas', marketCap: 28e9 },
    { symbol: 'PXD', name: 'Pioneer Natural Resources', industry: 'Oil & Gas', marketCap: 55e9 },
    { symbol: 'WMB', name: 'Williams Companies', industry: 'Midstream', marketCap: 45e9 },
    { symbol: 'KMI', name: 'Kinder Morgan', industry: 'Midstream', marketCap: 40e9 },
    { symbol: 'OKE', name: 'ONEOK', industry: 'Midstream', marketCap: 55e9 },
  ],
  'Industrials': [
    { symbol: 'CAT', name: 'Caterpillar', industry: 'Heavy Machinery', marketCap: 170e9 },
    { symbol: 'RTX', name: 'RTX Corporation', industry: 'Aerospace & Defense', marketCap: 150e9 },
    { symbol: 'HON', name: 'Honeywell', industry: 'Aerospace & Defense', marketCap: 140e9 },
    { symbol: 'UNP', name: 'Union Pacific', industry: 'Railroads', marketCap: 150e9 },
    { symbol: 'BA', name: 'Boeing', industry: 'Aerospace & Defense', marketCap: 130e9 },
    { symbol: 'UPS', name: 'United Parcel Service', industry: 'Shipping', marketCap: 120e9 },
    { symbol: 'DE', name: 'Deere & Company', industry: 'Farm Machinery', marketCap: 120e9 },
    { symbol: 'LMT', name: 'Lockheed Martin', industry: 'Aerospace & Defense', marketCap: 120e9 },
    { symbol: 'GE', name: 'General Electric', industry: 'Aerospace & Defense', marketCap: 170e9 },
    { symbol: 'MMM', name: '3M Company', industry: 'Conglomerate', marketCap: 60e9 },
    { symbol: 'NSC', name: 'Norfolk Southern', industry: 'Railroads', marketCap: 55e9 },
    { symbol: 'NOC', name: 'Northrop Grumman', industry: 'Aerospace & Defense', marketCap: 75e9 },
    { symbol: 'GD', name: 'General Dynamics', industry: 'Aerospace & Defense', marketCap: 80e9 },
    { symbol: 'TDG', name: 'TransDigm Group', industry: 'Aerospace & Defense', marketCap: 65e9 },
    { symbol: 'HII', name: 'Huntington Ingalls', industry: 'Aerospace & Defense', marketCap: 12e9 },
    { symbol: 'LHX', name: 'L3Harris Technologies', industry: 'Aerospace & Defense', marketCap: 45e9 },
    { symbol: 'TXT', name: 'Textron Inc.', industry: 'Aerospace & Defense', marketCap: 18e9 },
    { symbol: 'FAST', name: 'Fastenal Company', industry: 'Building Products', marketCap: 40e9 },
    { symbol: 'SHW', name: 'Sherwin-Williams', industry: 'Building Products', marketCap: 85e9 },
    { symbol: 'VMC', name: 'Vulcan Materials', industry: 'Building Products', marketCap: 30e9 },
    { symbol: 'MLM', name: 'Martin Marietta Materials', industry: 'Building Products', marketCap: 35e9 },
    { symbol: 'WM', name: 'Waste Management', industry: 'Waste Management', marketCap: 80e9 },
    { symbol: 'RSG', name: 'Republic Services', industry: 'Waste Management', marketCap: 60e9 },
    { symbol: 'ETN', name: 'Eaton Corporation', industry: 'Electrical Equipment', marketCap: 110e9 },
    { symbol: 'EMR', name: 'Emerson Electric', industry: 'Electrical Equipment', marketCap: 60e9 },
    { symbol: 'ROK', name: 'Rockwell Automation', industry: 'Electrical Equipment', marketCap: 35e9 },
  ],
  'Communication Services': [
    { symbol: 'GOOG', name: 'Alphabet Inc.', industry: 'Internet Services', marketCap: 1800e9 },
    { symbol: 'DIS', name: 'Walt Disney', industry: 'Entertainment', marketCap: 200e9 },
    { symbol: 'NFLX', name: 'Netflix', industry: 'Streaming', marketCap: 250e9 },
    { symbol: 'CMCSA', name: 'Comcast', industry: 'Cable', marketCap: 160e9 },
    { symbol: 'VZ', name: 'Verizon', industry: 'Telecom', marketCap: 170e9 },
    { symbol: 'T', name: 'AT&T', industry: 'Telecom', marketCap: 140e9 },
    { symbol: 'TMUS', name: 'T-Mobile', industry: 'Telecom', marketCap: 200e9 },
    { symbol: 'EA', name: 'Electronic Arts', industry: 'Gaming', marketCap: 38e9 },
    { symbol: 'TTWO', name: 'Take-Two Interactive', industry: 'Gaming', marketCap: 30e9 },
    { symbol: 'RBLX', name: 'Roblox Corporation', industry: 'Gaming', marketCap: 28e9 },
    { symbol: 'SNAP', name: 'Snap Inc.', industry: 'Social Media', marketCap: 18e9 },
    { symbol: 'PINS', name: 'Pinterest', industry: 'Social Media', marketCap: 20e9 },
    { symbol: 'WBD', name: 'Warner Bros. Discovery', industry: 'Entertainment', marketCap: 25e9 },
    { symbol: 'PARA', name: 'Paramount Global', industry: 'Entertainment', marketCap: 10e9 },
  ],
  'Utilities': [
    { symbol: 'NEE', name: 'NextEra Energy', industry: 'Utilities', marketCap: 150e9 },
    { symbol: 'DUK', name: 'Duke Energy', industry: 'Utilities', marketCap: 80e9 },
    { symbol: 'SO', name: 'Southern Company', industry: 'Utilities', marketCap: 85e9 },
    { symbol: 'AEP', name: 'American Electric Power', industry: 'Utilities', marketCap: 50e9 },
    { symbol: 'XEL', name: 'Xcel Energy', industry: 'Utilities', marketCap: 35e9 },
    { symbol: 'D', name: 'Dominion Energy', industry: 'Utilities', marketCap: 45e9 },
    { symbol: 'SRE', name: 'Sempra Energy', industry: 'Utilities', marketCap: 50e9 },
  ],
  'Real Estate': [
    { symbol: 'AMT', name: 'American Tower', industry: 'REITs', marketCap: 100e9 },
    { symbol: 'PLD', name: 'Prologis', industry: 'REITs', marketCap: 110e9 },
    { symbol: 'EQIX', name: 'Equinix', industry: 'Data Centers', marketCap: 75e9 },
    { symbol: 'O', name: 'Realty Income', industry: 'REITs', marketCap: 45e9 },
    { symbol: 'SPG', name: 'Simon Property Group', industry: 'REITs', marketCap: 50e9 },
    { symbol: 'VICI', name: 'VICI Properties', industry: 'REITs', marketCap: 35e9 },
    { symbol: 'CCI', name: 'Crown Castle', industry: 'REITs', marketCap: 45e9 },
  ],
};

export function findSectorForSymbol(symbol: string): { sector: string; industry: string } | null {
  const upperSymbol = symbol.toUpperCase();
  for (const [sector, stocks] of Object.entries(STOCKS_BY_SECTOR)) {
    const stock = stocks.find(s => s.symbol === upperSymbol);
    if (stock) {
      return { sector, industry: stock.industry };
    }
  }
  return null;
}
