export interface StarterRule {
  name: string;
  description: string;
  category: string;
  severity: 'auto_reject' | 'critical' | 'warning' | 'info';
  isAutoReject: boolean;
  ruleCode: string;
  formula?: string;
  order: number;
}

export const STARTER_RULES: StarterRule[] = [
  // === AUTO-REJECT RULES (Instant 0 Score) ===
  {
    name: "Price below 50 SMA during base formation",
    description: "Never trade stocks with price below 50 SMA during base formation - indicates weakness",
    category: "auto_reject",
    severity: "auto_reject",
    isAutoReject: true,
    ruleCode: "PRICE_BELOW_50SMA",
    order: 1,
  },
  {
    name: "50 SMA falling (counter-trend)",
    description: "Never trade counter-trend when 50 SMA is falling",
    category: "auto_reject",
    severity: "auto_reject",
    isAutoReject: true,
    ruleCode: "50SMA_FALLING",
    order: 2,
  },
  {
    name: "Stop loss >5% from entry",
    description: "Never exceed 5% stop loss from entry (hard limit)",
    category: "auto_reject",
    severity: "auto_reject",
    isAutoReject: true,
    ruleCode: "STOP_TOO_WIDE",
    formula: "Stop % = (Entry - Stop) / Entry × 100 > 5%",
    order: 3,
  },
  {
    name: "Extension ≥8% from 50 SMA",
    description: "Never buy stocks at 8%+ extension from 50 SMA - at/past profit-taking zone",
    category: "auto_reject",
    severity: "auto_reject",
    isAutoReject: true,
    ruleCode: "EXTENSION_8PCT",
    formula: "Extension = (Price - 50SMA) / 50SMA × 100 ≥ 8%",
    order: 4,
  },
  {
    name: "Risk/Reward ratio <2:1",
    description: "Never take trades with less than 2:1 risk/reward ratio",
    category: "auto_reject",
    severity: "auto_reject",
    isAutoReject: true,
    ruleCode: "RR_BELOW_2",
    formula: "R:R = (Target - Entry) / (Entry - Stop) < 2",
    order: 5,
  },
  {
    name: "No invalidation/stop defined",
    description: "Must always have a clear invalidation point and stop loss",
    category: "auto_reject",
    severity: "auto_reject",
    isAutoReject: true,
    ruleCode: "NO_STOP_DEFINED",
    order: 6,
  },
  {
    name: "Extreme chase >2.0 ATR above AVWAP (swing)",
    description: "Entry too far above anchored VWAP for swing trades",
    category: "auto_reject",
    severity: "auto_reject",
    isAutoReject: true,
    ruleCode: "EXTREME_CHASE_SWING",
    formula: "Entry > AVWAP + (2.0 × ATR)",
    order: 7,
  },
  {
    name: "Extreme chase >1.5 ATR above AVWAP (intraday)",
    description: "Entry too far above anchored VWAP for intraday trades",
    category: "auto_reject",
    severity: "auto_reject",
    isAutoReject: true,
    ruleCode: "EXTREME_CHASE_INTRADAY",
    formula: "Entry > AVWAP + (1.5 × ATR)",
    order: 8,
  },
  {
    name: "Trade conflicts with market regime (Headwind)",
    description: "Don't trade against market regime without exceptional edge justification",
    category: "auto_reject",
    severity: "auto_reject",
    isAutoReject: true,
    ruleCode: "REGIME_CONFLICT",
    order: 9,
  },

  // === 8% PROFIT-TAKING RULE ===
  {
    name: "Take profits at 8% extension from 50 SMA",
    description: "Primary profit-taking zone - don't let winners become losers",
    category: "profit_taking",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "PROFIT_8PCT_50SMA",
    formula: "Target = 50 SMA × 1.08",
    order: 10,
  },
  {
    name: "Never buy at 7.5%+ extension from 50 SMA",
    description: "Too close to sell zone - no room to run",
    category: "profit_taking",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "NO_BUY_75PCT_EXT",
    order: 11,
  },

  // === RISK/REWARD REQUIREMENTS ===
  {
    name: "Minimum R:R ratio 4:1",
    description: "Target trades with at least 4:1 risk/reward for quality setups",
    category: "risk",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "MIN_RR_4",
    formula: "R:R = (Target - Entry) / (Entry - Stop) ≥ 4",
    order: 12,
  },
  {
    name: "Target R:R ratio 6:1 to 8:1",
    description: "Ideal risk/reward range for high-quality setups",
    category: "risk",
    severity: "info",
    isAutoReject: false,
    ruleCode: "TARGET_RR_6_8",
    order: 13,
  },

  // === STOP LOSS RULES ===
  {
    name: "Choppy market: Use LOD following entry as initial stop",
    description: "In choppy markets, use low of day following entry for initial stop",
    category: "stop_loss",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "CHOPPY_LOD_STOP",
    order: 14,
  },
  {
    name: "Lock in profits: Move stop to breakeven at 2-3% gain",
    description: "When making 2-3% profit, move stop to ensure no loss",
    category: "stop_loss",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "LOCK_BREAKEVEN",
    order: 15,
  },
  {
    name: "NEVER move stop away from entry",
    description: "Only move stops toward entry or toward profit - never widen",
    category: "stop_loss",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "NEVER_WIDEN_STOP",
    order: 16,
  },
  {
    name: "Choppy market: Sell 1/4 to 1/3 same day to lock gains",
    description: "In choppy markets with 2-3% profit, take some off to protect against overnight gap",
    category: "stop_loss",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "CHOPPY_PARTIAL_EXIT",
    order: 17,
  },

  // === MA STRUCTURE REQUIREMENTS ===
  {
    name: "Price must be above 50 SMA during entire base",
    description: "Mandatory - no base formation with price below 50 SMA",
    category: "ma_structure",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "PRICE_ABOVE_50SMA_BASE",
    order: 18,
  },
  {
    name: "50 SMA must be rising (not flat or falling)",
    description: "Trend must be established before entry",
    category: "ma_structure",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "50SMA_RISING",
    order: 19,
  },
  {
    name: "Price must be above 200 SMA at entry",
    description: "Long-term trend confirmation required",
    category: "ma_structure",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "ABOVE_200SMA",
    order: 20,
  },
  {
    name: "50 SMA should be above 200 SMA (Stage 2 uptrend)",
    description: "Ideal trend structure for breakout trades",
    category: "ma_structure",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "50_ABOVE_200",
    order: 21,
  },
  {
    name: "Extension 0-3% from 50 SMA: Ideal",
    description: "Maximum room to run with minimal risk",
    category: "ma_structure",
    severity: "info",
    isAutoReject: false,
    ruleCode: "EXT_0_3PCT_IDEAL",
    order: 22,
  },
  {
    name: "Extension 3-6% from 50 SMA: Acceptable",
    description: "Some room but getting extended",
    category: "ma_structure",
    severity: "info",
    isAutoReject: false,
    ruleCode: "EXT_3_6PCT_OK",
    order: 23,
  },
  {
    name: "Extension 6-7.5% from 50 SMA: Caution",
    description: "Near resistance, elevated risk above 5%",
    category: "ma_structure",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "EXT_6_75PCT_CAUTION",
    order: 24,
  },
  {
    name: "Extension from 200 SMA >40%: Very risky",
    description: "High pullback probability when very extended from 200 SMA",
    category: "ma_structure",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "EXT_200SMA_40PCT",
    order: 25,
  },

  // === BASE/PATTERN QUALITY ===
  {
    name: "Volume contracted 30%+ during base formation",
    description: "Ideal volume contraction shows accumulation and supply drying up",
    category: "base_quality",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "VOLUME_CONTRACTION_30",
    order: 26,
  },
  {
    name: "Base duration: 5-12 weeks ideal",
    description: "Proper base formation time for reliable breakouts",
    category: "base_quality",
    severity: "info",
    isAutoReject: false,
    ruleCode: "BASE_5_12_WEEKS",
    order: 27,
  },
  {
    name: "First base off lows: Best odds",
    description: "First base has highest success probability",
    category: "base_quality",
    severity: "info",
    isAutoReject: false,
    ruleCode: "FIRST_BASE_BEST",
    order: 28,
  },
  {
    name: "Third+ base: Higher failure risk",
    description: "Third or later bases have significantly higher failure rates",
    category: "base_quality",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "THIRD_BASE_WARNING",
    order: 29,
  },
  {
    name: "Cup depth: 15-35% (25% ideal)",
    description: "Proper cup depth for Cup & Handle patterns",
    category: "base_quality",
    severity: "info",
    isAutoReject: false,
    ruleCode: "CUP_DEPTH_15_35",
    order: 30,
  },
  {
    name: "Cup shape: U-shaped (NOT V-shaped)",
    description: "V-shaped cups lack proper base formation",
    category: "base_quality",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "CUP_U_SHAPE",
    order: 31,
  },
  {
    name: "Handle depth: <15% of cup depth, <20% absolute",
    description: "Handle should be shallow relative to cup",
    category: "base_quality",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "HANDLE_SHALLOW",
    order: 32,
  },
  {
    name: "High Tight Flag: Prior gain 40-120%+ in 4-8 weeks",
    description: "HTF requires strong prior move before consolidation",
    category: "base_quality",
    severity: "info",
    isAutoReject: false,
    ruleCode: "HTF_PRIOR_GAIN",
    order: 33,
  },
  {
    name: "VCP: 3+ contraction stages with each pullback shallower",
    description: "Proper VCP shows progressively tighter ranges",
    category: "base_quality",
    severity: "info",
    isAutoReject: false,
    ruleCode: "VCP_3_CONTRACTIONS",
    order: 34,
  },

  // === BREAKOUT QUALITY ===
  {
    name: "Breakout volume 150%+ above average: Excellent",
    description: "Strong institutional buying on breakout",
    category: "breakout",
    severity: "info",
    isAutoReject: false,
    ruleCode: "VOLUME_150PCT_EXCELLENT",
    order: 35,
  },
  {
    name: "Breakout volume 100-150% above average: Strong",
    description: "Good volume confirmation on breakout",
    category: "breakout",
    severity: "info",
    isAutoReject: false,
    ruleCode: "VOLUME_100_150_STRONG",
    order: 36,
  },
  {
    name: "Breakout volume <50% above average: Weak",
    description: "Insufficient conviction on breakout - higher failure rate",
    category: "breakout",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "VOLUME_BELOW_50_WEAK",
    order: 37,
  },
  {
    name: "Decisive move above resistance required",
    description: "Clean breakout without immediate pullback",
    category: "breakout",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "DECISIVE_BREAK",
    order: 38,
  },

  // === POSITION SIZING ===
  {
    name: "Score 90-100: Full position (100%)",
    description: "Excellent setup deserves full position sizing",
    category: "position_sizing",
    severity: "info",
    isAutoReject: false,
    ruleCode: "SIZE_90_100_FULL",
    order: 39,
  },
  {
    name: "Score 75-89: Full or slightly reduced (75-100%)",
    description: "Good setup with some concerns",
    category: "position_sizing",
    severity: "info",
    isAutoReject: false,
    ruleCode: "SIZE_75_89_REDUCE",
    order: 40,
  },
  {
    name: "Score 60-74: Reduced position (50-75%)",
    description: "Marginal setup - trade small if at all",
    category: "position_sizing",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "SIZE_60_74_SMALL",
    order: 41,
  },
  {
    name: "Score <60: No position (0%)",
    description: "Poor setup - do not trade",
    category: "position_sizing",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "SIZE_BELOW_60_NONE",
    order: 42,
  },
  {
    name: "Adjust size to keep dollar risk constant",
    description: "Wider stop = smaller position; tighter stop = larger position",
    category: "position_sizing",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "CONSTANT_DOLLAR_RISK",
    formula: "Position = Risk$ / (Entry - Stop)",
    order: 43,
  },

  // === ENTRY TIMING ===
  {
    name: "Enter at or near breakout level",
    description: "Best entries are at the pivot point",
    category: "entry",
    severity: "info",
    isAutoReject: false,
    ruleCode: "ENTRY_AT_PIVOT",
    order: 44,
  },
  {
    name: "Entry within 5% of pivot acceptable",
    description: "Some extension is okay but watch for chasing",
    category: "entry",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "ENTRY_WITHIN_5PCT",
    order: 45,
  },
  {
    name: "Chasing >5% past pivot: Poor entry",
    description: "Avoid entries too far from pivot point",
    category: "entry",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "CHASE_5PCT_BAD",
    order: 46,
  },
  {
    name: "Confirm volume on breakout before entering",
    description: "Wait for volume confirmation, not just price move",
    category: "entry",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "CONFIRM_VOLUME",
    order: 47,
  },

  // === PROFIT-TAKING ===
  {
    name: "Scale out: Take 1/3 off at 8% from 50 SMA",
    description: "First resistance level - lock in some profit",
    category: "exit",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "SCALE_8PCT_FIRST",
    order: 48,
  },
  {
    name: "Scale out: Take 1/3 at measured move target",
    description: "Second profit target based on pattern measurement",
    category: "exit",
    severity: "info",
    isAutoReject: false,
    ruleCode: "SCALE_MEASURED_MOVE",
    order: 49,
  },
  {
    name: "Exit immediately if stop hit (no exceptions)",
    description: "Discipline is key - always honor your stop",
    category: "exit",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "EXIT_STOP_HIT",
    order: 50,
  },
  {
    name: "Exit if pattern fails (breaks back into base)",
    description: "Failed breakout requires immediate action",
    category: "exit",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "EXIT_PATTERN_FAIL",
    order: 51,
  },
  {
    name: "Exit if 50 SMA turns down",
    description: "Trend change signal - respect the moving average",
    category: "exit",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "EXIT_50SMA_DOWN",
    order: 52,
  },

  // === MARKET REGIME ADJUSTMENTS ===
  {
    name: "Bull market: Can tolerate 25-30% extension from 200 SMA",
    description: "More room for extended moves in strong markets",
    category: "market_regime",
    severity: "info",
    isAutoReject: false,
    ruleCode: "BULL_EXT_TOLERANCE",
    order: 53,
  },
  {
    name: "Choppy market: Demand <20% extension from 200 SMA",
    description: "Tighter requirements in uncertain markets",
    category: "market_regime",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "CHOPPY_EXT_TIGHT",
    order: 54,
  },
  {
    name: "Choppy market: Take quick profits (3-5%)",
    description: "Don't wait for full targets in choppy conditions",
    category: "market_regime",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "CHOPPY_QUICK_PROFIT",
    order: 55,
  },
  {
    name: "Bear market: Only trade strongest relative strength",
    description: "Very selective in down markets - only A+ setups",
    category: "market_regime",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "BEAR_RS_ONLY",
    order: 56,
  },
  {
    name: "Bear market: Avoid trades scoring <85",
    description: "Raise the bar significantly in adverse conditions",
    category: "market_regime",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "BEAR_MIN_85",
    order: 57,
  },

  // === MINIMUM STANDARDS ===
  {
    name: "Score <50: Reject (don't trade)",
    description: "Poor quality setup - pass completely",
    category: "general",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "MIN_SCORE_50",
    order: 58,
  },
  {
    name: "Score 50-59: Watch only (no entry)",
    description: "Setup has potential but not ready yet",
    category: "general",
    severity: "warning",
    isAutoReject: false,
    ruleCode: "SCORE_50_59_WATCH",
    order: 59,
  },
  {
    name: "Never hope a losing trade comes back",
    description: "Cut losses - hope is not a strategy",
    category: "general",
    severity: "critical",
    isAutoReject: false,
    ruleCode: "NO_HOPE_TRADING",
    order: 60,
  },
  {
    name: "A rejected trade is better than a losing one",
    description: "Preservation of capital is paramount",
    category: "general",
    severity: "info",
    isAutoReject: false,
    ruleCode: "REJECT_OVER_LOSE",
    order: 61,
  },
];

export const RULE_CATEGORIES = [
  { value: "auto_reject", label: "Auto-Reject", description: "Instant trade rejection" },
  { value: "profit_taking", label: "Profit Taking", description: "When to take profits" },
  { value: "stop_loss", label: "Stop Loss", description: "Stop placement and management" },
  { value: "ma_structure", label: "MA Structure", description: "Moving average requirements" },
  { value: "base_quality", label: "Base Quality", description: "Pattern formation quality" },
  { value: "breakout", label: "Breakout", description: "Breakout confirmation" },
  { value: "position_sizing", label: "Position Sizing", description: "How much to trade" },
  { value: "entry", label: "Entry", description: "Entry timing rules" },
  { value: "exit", label: "Exit", description: "Exit timing rules" },
  { value: "risk", label: "Risk", description: "Risk management" },
  { value: "market_regime", label: "Market Regime", description: "Market condition adjustments" },
  { value: "general", label: "General", description: "Core philosophy" },
];

export const SEVERITY_LEVELS = [
  { value: "auto_reject", label: "Auto-Reject", color: "red", description: "Trade will be instantly rejected" },
  { value: "critical", label: "Critical", color: "orange", description: "Major rule that should rarely be broken" },
  { value: "warning", label: "Warning", color: "yellow", description: "Important rule to consider" },
  { value: "info", label: "Info", color: "blue", description: "Good practice / nice to have" },
];
