import React, { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { Loader2, Sparkles, Check, AlertCircle, Play } from "lucide-react";

interface DataLinkProvides {
  linkType: string;
  paramName: string;
}

interface DataLinkConsumes {
  paramName: string;
  dataKey: string;
}

interface GeneratedIndicator {
  name: string;
  category: string;
  description: string;
  params: Array<{
    name: string;
    label: string;
    type: "number" | "select" | "boolean";
    defaultValue: any;
    options?: string[];
    min?: number;
    max?: number;
    step?: number;
    autoLink?: { linkType: string };
  }>;
  logicDefinition: {
    rules: Array<{
      condition: string;
      operator?: string;
      threshold?: number | string;
      lookback?: number;
      consecutiveDays?: number;
    }>;
    combineLogic: "AND" | "OR";
  };
  provides?: DataLinkProvides[];
  consumes?: DataLinkConsumes[];
}

interface CustomIndicatorPreviewDialogProps {
  open: boolean;
  onClose: () => void;
  indicator: GeneratedIndicator;
  aiPrompt: string;
  onSaved: (savedIndicator: any) => void;
}

const COMMON_LINK_TYPES = [
  { value: "basePeriod", label: "Base Period", desc: "Length of detected pattern" },
  { value: "sequenceOffset", label: "Sequence Offset", desc: "Bars to skip for chaining" },
  { value: "priceChange", label: "Price Change", desc: "Measured price movement" },
  { value: "patternBar", label: "Pattern Bar", desc: "Bar where pattern occurred" },
];

const COMMON_DATA_KEYS = [
  { value: "detectedPeriod", label: "Detected Period", desc: "Period from upstream indicator" },
  { value: "baseStartBar", label: "Base Start Bar", desc: "Where upstream base started" },
  { value: "baseEndBar", label: "Base End Bar", desc: "Where upstream base ended" },
  { value: "patternEndBar", label: "Pattern End Bar", desc: "Where upstream pattern ended" },
];

const RULE_TOOLTIPS: Record<string, string> = {
  "PRICE_ABOVE": "Price is above a threshold value",
  "PRICE_BELOW": "Price is below a threshold value",
  "PRICE_BETWEEN": "Price is within a range",
  "CLOSE_ABOVE_OPEN": "Candle closed higher than it opened (bullish)",
  "CLOSE_BELOW_OPEN": "Candle closed lower than it opened (bearish)",
  "VOLUME_ABOVE_AVG": "Volume exceeds the average by a multiplier",
  "VOLUME_ABOVE_THRESHOLD": "Volume exceeds a specific number",
  "CONSECUTIVE_UP_DAYS": "Price closed higher for N consecutive days",
  "CONSECUTIVE_DOWN_DAYS": "Price closed lower for N consecutive days",
  "SMA_CROSS_ABOVE": "Short SMA crossed above long SMA",
  "SMA_CROSS_BELOW": "Short SMA crossed below long SMA",
  "PRICE_ABOVE_SMA": "Current price is above the SMA",
  "PRICE_BELOW_SMA": "Current price is below the SMA",
  "GAP_UP": "Price gapped up from prior close",
  "GAP_DOWN": "Price gapped down from prior close",
  "GAP_UP_PCT": "Gapped up by at least X%",
  "GAP_DOWN_PCT": "Gapped down by at least X%",
  "HIGHER_HIGH": "Made a higher high than previous bar",
  "LOWER_LOW": "Made a lower low than previous bar",
  "BREAKOUT_NEW_HIGH": "Broke out to a new high over lookback period",
  "BREAKDOWN_NEW_LOW": "Broke down to a new low over lookback period",
  "INSIDE_BAR": "Bar's range is within prior bar's range (consolidation)",
  "OUTSIDE_BAR": "Bar's range exceeds prior bar's range (expansion)",
  "PRICE_CHANGE_PCT": "Price changed by X% over N bars",
  "MOMENTUM_INCREASING": "Price momentum is accelerating",
  "MOMENTUM_DECREASING": "Price momentum is decelerating",
};

function autoGenerateDataLinks(params: GeneratedIndicator["params"]): { provides: DataLinkProvides[], consumes: DataLinkConsumes[] } {
  const provides: DataLinkProvides[] = [];
  const consumes: DataLinkConsumes[] = [];
  
  // Get all numeric params for potential linking
  const numericParams = params.filter(p => p.type === "number");
  
  // Auto-detect output params - prefer period/lookback, but fall back to first numeric param
  const periodParam = params.find(p => 
    p.name === "period" || p.name === "lookback" || p.name === "bars" || 
    p.name === "window" || p.name === "length"
  ) || numericParams[0];
  
  if (periodParam) {
    provides.push({ linkType: "sequenceOffset", paramName: periodParam.name });
  }
  
  // Auto-detect input params - prefer skipBars/startBar, but fall back to a suitable param
  const skipParam = params.find(p => 
    p.name === "skipBars" || p.name === "startBar" || p.name === "offset" ||
    p.name === "start" || p.name === "from"
  );
  
  // If no explicit skip param, use the first numeric param that isn't already used for output
  const inputParam = skipParam || numericParams.find(p => p.name !== periodParam?.name);
  
  if (inputParam) {
    consumes.push({ paramName: inputParam.name, dataKey: "detectedPeriod" });
  } else if (numericParams.length > 0) {
    // If only one param, use it for both (it can receive upstream data and provide downstream)
    consumes.push({ paramName: numericParams[0].name, dataKey: "detectedPeriod" });
  }
  
  return { provides, consumes };
}

export function CustomIndicatorPreviewDialog({
  open,
  onClose,
  indicator,
  aiPrompt,
  onSaved,
}: CustomIndicatorPreviewDialogProps) {
  const { toast } = useToast();
  const [showAdvanced, setShowAdvanced] = useState(false);
  
  // Auto-populate data linking defaults if not provided
  const indicatorWithDefaults = React.useMemo(() => {
    if (!indicator) return indicator;
    const hasProvides = indicator.provides && indicator.provides.length > 0;
    const hasConsumes = indicator.consumes && indicator.consumes.length > 0;
    
    if (!hasProvides && !hasConsumes) {
      const autoLinks = autoGenerateDataLinks(indicator.params);
      return {
        ...indicator,
        provides: autoLinks.provides,
        consumes: autoLinks.consumes,
      };
    }
    return indicator;
  }, [indicator]);
  
  const [editedIndicator, setEditedIndicator] = useState(indicatorWithDefaults);
  const [testSymbol, setTestSymbol] = useState("AAPL");
  const [testResult, setTestResult] = useState<{ pass: boolean; symbol: string } | null>(null);
  const [isTesting, setIsTesting] = useState(false);

  // Update when indicator changes
  React.useEffect(() => {
    if (indicatorWithDefaults) {
      setEditedIndicator(indicatorWithDefaults);
    }
  }, [indicatorWithDefaults]);

  if (!indicator) {
    return null;
  }

  const saveIndicatorMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest(
        "POST",
        "/api/bigidea/custom-indicators",
        {
          ...editedIndicator,
          aiPrompt,
        }
      );
      return await response.json();
    },
    onSuccess: (data) => {
      toast({
        title: "Custom Indicator Saved",
        description: `"${editedIndicator.name}" has been added to your library.`,
      });
      onSaved(data.indicator);
      onClose();
    },
    onError: (error: any) => {
      toast({
        title: "Save Failed",
        description: error?.message || "Failed to save custom indicator",
        variant: "destructive",
      });
    },
  });

  const testIndicatorMutation = useMutation({
    mutationFn: async (symbol: string) => {
      const response = await apiRequest(
        "POST",
        "/api/bigidea/custom-indicators/test",
        {
          symbol,
          logicDefinition: editedIndicator.logicDefinition,
          params: editedIndicator.params.reduce((acc, p) => {
            acc[p.name] = p.defaultValue;
            return acc;
          }, {} as Record<string, any>),
          timeframe: "daily",
        }
      );
      return await response.json();
    },
    onSuccess: (data) => {
      setTestResult({ pass: data.pass, symbol: testSymbol });
      setIsTesting(false);
    },
    onError: (error: any) => {
      toast({
        title: "Test Failed",
        description: error?.message || "Failed to test indicator",
        variant: "destructive",
      });
      setIsTesting(false);
    },
  });

  const handleTest = () => {
    if (!testSymbol) {
      toast({
        title: "Enter a Symbol",
        description: "Please enter a stock symbol to test the indicator.",
        variant: "destructive",
      });
      return;
    }
    setIsTesting(true);
    testIndicatorMutation.mutate(testSymbol);
  };

  const handleSave = () => {
    saveIndicatorMutation.mutate();
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl max-h-[90vh]">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-blue-500" />
            <DialogTitle>Custom Indicator Preview</DialogTitle>
          </div>
          <DialogDescription>
            Review and test the AI-generated indicator before saving to your library.
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className="max-h-[60vh] pr-4">
          <div className="space-y-4 py-4">
            {/* Basic Info */}
            <div className="space-y-2">
              <Label htmlFor="indicator-name">Indicator Name</Label>
              <Input
                id="indicator-name"
                value={editedIndicator.name}
                onChange={(e) => setEditedIndicator({ ...editedIndicator, name: e.target.value })}
                className="bg-zinc-900 border-zinc-700"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="indicator-category">Category</Label>
              <Select
                value={editedIndicator.category}
                onValueChange={(value) => setEditedIndicator({ ...editedIndicator, category: value })}
              >
                <SelectTrigger id="indicator-category" className="bg-zinc-900 border-zinc-700">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Price Action">Price Action</SelectItem>
                  <SelectItem value="Volume">Volume</SelectItem>
                  <SelectItem value="Momentum">Momentum</SelectItem>
                  <SelectItem value="Consolidation">Consolidation</SelectItem>
                  <SelectItem value="Moving Averages">Moving Averages</SelectItem>
                  <SelectItem value="Volatility">Volatility</SelectItem>
                  <SelectItem value="Relative Strength">Relative Strength</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="indicator-description">Description</Label>
              <Textarea
                id="indicator-description"
                value={editedIndicator.description}
                onChange={(e) => setEditedIndicator({ ...editedIndicator, description: e.target.value })}
                className="bg-zinc-900 border-zinc-700 min-h-[80px]"
              />
            </div>

            {/* Parameters - Editable */}
            {editedIndicator.params.length > 0 && (
              <div className="space-y-2">
                <Label>Parameters (editable)</Label>
                <div className="p-3 bg-zinc-900/50 border border-zinc-800 rounded-lg space-y-4">
                  {editedIndicator.params.map((param, idx) => (
                    <div key={idx} className="space-y-2 p-2 bg-zinc-950/50 rounded border border-zinc-800">
                      <div className="flex items-center gap-2">
                        <Input
                          value={param.label}
                          onChange={(e) => {
                            const newParams = [...editedIndicator.params];
                            newParams[idx] = { ...newParams[idx], label: e.target.value };
                            setEditedIndicator({ ...editedIndicator, params: newParams });
                          }}
                          className="bg-zinc-900 border-zinc-700 text-sm h-8 flex-1"
                          placeholder="Parameter label"
                        />
                        <Badge variant="outline" className="font-mono text-xs">
                          {param.name}
                        </Badge>
                      </div>
                      <div className="grid grid-cols-4 gap-2">
                        <div className="space-y-1">
                          <span className="text-[10px] text-zinc-500 uppercase">Default</span>
                          <Input
                            type="number"
                            value={param.defaultValue}
                            onChange={(e) => {
                              const newParams = [...editedIndicator.params];
                              newParams[idx] = { ...newParams[idx], defaultValue: parseFloat(e.target.value) || 0 };
                              setEditedIndicator({ ...editedIndicator, params: newParams });
                            }}
                            className="bg-zinc-900 border-zinc-700 text-sm h-8"
                            step={param.step || 0.01}
                          />
                        </div>
                        <div className="space-y-1">
                          <span className="text-[10px] text-zinc-500 uppercase">Min</span>
                          <Input
                            type="number"
                            value={param.min ?? 0.01}
                            onChange={(e) => {
                              const newParams = [...editedIndicator.params];
                              newParams[idx] = { ...newParams[idx], min: parseFloat(e.target.value) || 0.01 };
                              setEditedIndicator({ ...editedIndicator, params: newParams });
                            }}
                            className="bg-zinc-900 border-zinc-700 text-sm h-8"
                            step={0.01}
                          />
                        </div>
                        <div className="space-y-1">
                          <span className="text-[10px] text-zinc-500 uppercase">Max</span>
                          <Input
                            type="number"
                            value={param.max ?? 1000}
                            onChange={(e) => {
                              const newParams = [...editedIndicator.params];
                              newParams[idx] = { ...newParams[idx], max: parseFloat(e.target.value) || 1000 };
                              setEditedIndicator({ ...editedIndicator, params: newParams });
                            }}
                            className="bg-zinc-900 border-zinc-700 text-sm h-8"
                            step={1}
                          />
                        </div>
                        <div className="space-y-1">
                          <span className="text-[10px] text-zinc-500 uppercase">Step</span>
                          <Input
                            type="number"
                            value={param.step ?? 0.01}
                            onChange={(e) => {
                              const newParams = [...editedIndicator.params];
                              newParams[idx] = { ...newParams[idx], step: parseFloat(e.target.value) || 0.01 };
                              setEditedIndicator({ ...editedIndicator, params: newParams });
                            }}
                            className="bg-zinc-900 border-zinc-700 text-sm h-8"
                            step={0.01}
                          />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Logic Definition with Tooltips */}
            <div className="space-y-2">
              <Label>Logic Rules</Label>
              <div className="p-3 bg-zinc-900/50 border border-zinc-800 rounded-lg space-y-2">
                <div className="text-xs text-zinc-500 uppercase font-semibold">
                  Combine: {editedIndicator.logicDefinition.combineLogic}
                </div>
                {editedIndicator.logicDefinition.rules.map((rule, idx) => (
                  <div key={idx} className="flex items-start gap-2 p-2 bg-zinc-950/50 rounded border border-zinc-800">
                    <Badge variant="secondary" className="text-[10px] mt-0.5">
                      {idx + 1}
                    </Badge>
                    <div className="flex-1 text-sm space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="font-semibold text-zinc-200">{rule.condition}</span>
                        {RULE_TOOLTIPS[rule.condition] && (
                          <span 
                            className="text-[10px] text-blue-400 cursor-help border-b border-dotted border-blue-400"
                            title={RULE_TOOLTIPS[rule.condition]}
                          >
                            ?
                          </span>
                        )}
                      </div>
                      {RULE_TOOLTIPS[rule.condition] && (
                        <div className="text-[11px] text-zinc-500 italic">
                          {RULE_TOOLTIPS[rule.condition]}
                        </div>
                      )}
                      {rule.consecutiveDays && (
                        <div className="text-xs text-zinc-400">Consecutive Days: {rule.consecutiveDays}</div>
                      )}
                      {rule.lookback && (
                        <div className="text-xs text-zinc-400">Lookback: {rule.lookback} bars</div>
                      )}
                      {rule.threshold !== undefined && (
                        <div className="text-xs text-zinc-400">Threshold: {rule.threshold}</div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Advanced: Indicator Chaining (collapsible) */}
            <div className="space-y-2 pt-2 border-t border-zinc-800">
              <button
                type="button"
                onClick={() => setShowAdvanced(!showAdvanced)}
                className="flex items-center gap-2 text-sm text-zinc-400 hover:text-zinc-200 transition-colors"
              >
                <span className={`transition-transform ${showAdvanced ? 'rotate-90' : ''}`}>▶</span>
                Advanced: Indicator Chaining
                <span className="text-[10px] text-zinc-600">
                  ({(editedIndicator.provides?.length || 0)} out, {(editedIndicator.consumes?.length || 0)} in)
                </span>
              </button>
              
              {showAdvanced && (
                <div className="space-y-4 pl-4 animate-in slide-in-from-top-2">
                  <p className="text-xs text-zinc-500">
                    Chain this indicator with others. <strong>Outputs</strong> pass data to downstream indicators. 
                    <strong> Inputs</strong> receive data from upstream indicators.
                  </p>
                  
                  {/* Outputs (Provides) */}
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <Label className="text-xs">Outputs (what this indicator provides)</Label>
                      <Button
                        size="sm"
                        variant="outline"
                        className="h-6 text-xs"
                        onClick={() => {
                          const newProvides = [...(editedIndicator.provides || []), { linkType: "sequenceOffset", paramName: editedIndicator.params[0]?.name || "" }];
                          setEditedIndicator({ ...editedIndicator, provides: newProvides });
                        }}
                      >
                        + Add Output
                      </Button>
                    </div>
                    {(editedIndicator.provides && editedIndicator.provides.length > 0) ? (
                      <div className="space-y-2">
                        {editedIndicator.provides.map((provide, idx) => (
                          <div key={idx} className="flex items-center gap-2 p-2 bg-zinc-900/50 rounded border border-zinc-800">
                            <select
                              value={provide.paramName}
                              onChange={(e) => {
                                const newProvides = [...(editedIndicator.provides || [])];
                                newProvides[idx] = { ...newProvides[idx], paramName: e.target.value };
                                setEditedIndicator({ ...editedIndicator, provides: newProvides });
                              }}
                              className="bg-zinc-900 border border-zinc-700 rounded text-xs h-7 px-2"
                            >
                              <option value="">Param...</option>
                              {editedIndicator.params.map(p => (
                                <option key={p.name} value={p.name}>{p.label}</option>
                              ))}
                            </select>
                            <span className="text-zinc-500 text-xs">→</span>
                            <select
                              value={provide.linkType}
                              onChange={(e) => {
                                const newProvides = [...(editedIndicator.provides || [])];
                                newProvides[idx] = { ...newProvides[idx], linkType: e.target.value };
                                setEditedIndicator({ ...editedIndicator, provides: newProvides });
                              }}
                              className="bg-zinc-900 border border-zinc-700 rounded text-xs h-7 px-2 flex-1"
                            >
                              {COMMON_LINK_TYPES.map(lt => (
                                <option key={lt.value} value={lt.value}>{lt.label}</option>
                              ))}
                            </select>
                            <Button
                              size="sm"
                              variant="ghost"
                              className="h-6 w-6 p-0 text-red-400 hover:text-red-300"
                              onClick={() => {
                                const newProvides = (editedIndicator.provides || []).filter((_, i) => i !== idx);
                                setEditedIndicator({ ...editedIndicator, provides: newProvides });
                              }}
                            >
                              ×
                            </Button>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <div className="text-xs text-zinc-600 p-2 bg-zinc-900/30 rounded">
                        No outputs. Click "+ Add Output" to allow chaining to downstream indicators.
                      </div>
                    )}
                  </div>

                  {/* Inputs (Consumes) */}
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <Label className="text-xs">Inputs (what this indicator receives)</Label>
                      <Button
                        size="sm"
                        variant="outline"
                        className="h-6 text-xs"
                        onClick={() => {
                          const skipParam = editedIndicator.params.find(p => p.name === "skipBars" || p.name === "startBar" || p.name === "lookback");
                          const newConsumes = [...(editedIndicator.consumes || []), { paramName: skipParam?.name || editedIndicator.params[0]?.name || "", dataKey: "detectedPeriod" }];
                          setEditedIndicator({ ...editedIndicator, consumes: newConsumes });
                        }}
                      >
                        + Add Input
                      </Button>
                    </div>
                    {(editedIndicator.consumes && editedIndicator.consumes.length > 0) ? (
                      <div className="space-y-2">
                        {editedIndicator.consumes.map((consume, idx) => (
                          <div key={idx} className="flex items-center gap-2 p-2 bg-zinc-900/50 rounded border border-zinc-800">
                            <select
                              value={consume.dataKey}
                              onChange={(e) => {
                                const newConsumes = [...(editedIndicator.consumes || [])];
                                newConsumes[idx] = { ...newConsumes[idx], dataKey: e.target.value };
                                setEditedIndicator({ ...editedIndicator, consumes: newConsumes });
                              }}
                              className="bg-zinc-900 border border-zinc-700 rounded text-xs h-7 px-2 flex-1"
                            >
                              {COMMON_DATA_KEYS.map(dk => (
                                <option key={dk.value} value={dk.value}>{dk.label}</option>
                              ))}
                            </select>
                            <span className="text-zinc-500 text-xs">→</span>
                            <select
                              value={consume.paramName}
                              onChange={(e) => {
                                const newConsumes = [...(editedIndicator.consumes || [])];
                                newConsumes[idx] = { ...newConsumes[idx], paramName: e.target.value };
                                setEditedIndicator({ ...editedIndicator, consumes: newConsumes });
                              }}
                              className="bg-zinc-900 border border-zinc-700 rounded text-xs h-7 px-2"
                            >
                              <option value="">Param...</option>
                              {editedIndicator.params.map(p => (
                                <option key={p.name} value={p.name}>{p.label}</option>
                              ))}
                            </select>
                            <Button
                              size="sm"
                              variant="ghost"
                              className="h-6 w-6 p-0 text-red-400 hover:text-red-300"
                              onClick={() => {
                                const newConsumes = (editedIndicator.consumes || []).filter((_, i) => i !== idx);
                                setEditedIndicator({ ...editedIndicator, consumes: newConsumes });
                              }}
                            >
                              ×
                            </Button>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <div className="text-xs text-zinc-600 p-2 bg-zinc-900/30 rounded">
                        No inputs. Click "+ Add Input" to receive data from upstream indicators.
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>

            {/* Test Section */}
            <div className="space-y-2 pt-4 border-t border-zinc-800">
              <Label>Test Indicator</Label>
              <div className="flex gap-2">
                <Input
                  placeholder="Enter symbol (e.g., AAPL)"
                  value={testSymbol}
                  onChange={(e) => setTestSymbol(e.target.value.toUpperCase())}
                  className="bg-zinc-900 border-zinc-700"
                  onKeyDown={(e) => e.key === "Enter" && handleTest()}
                />
                <Button
                  onClick={handleTest}
                  disabled={isTesting || !testSymbol}
                  variant="outline"
                  size="sm"
                >
                  {isTesting ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <Play className="h-4 w-4" />
                  )}
                </Button>
              </div>

              {testResult && (
                <div className={`p-3 rounded-lg border ${
                  testResult.pass 
                    ? "bg-green-950/20 border-green-800/50 text-green-300" 
                    : "bg-red-950/20 border-red-800/50 text-red-300"
                }`}>
                  <div className="flex items-center gap-2 text-sm font-semibold">
                    {testResult.pass ? (
                      <>
                        <Check className="h-4 w-4" />
                        {testResult.symbol} PASSED
                      </>
                    ) : (
                      <>
                        <AlertCircle className="h-4 w-4" />
                        {testResult.symbol} FAILED
                      </>
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>
        </ScrollArea>

        <DialogFooter className="gap-2">
          <Button
            variant="outline"
            onClick={onClose}
            disabled={saveIndicatorMutation.isPending}
          >
            Cancel
          </Button>
          <Button
            onClick={handleSave}
            disabled={saveIndicatorMutation.isPending}
            className="bg-blue-600 hover:bg-blue-700"
          >
            {saveIndicatorMutation.isPending ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Saving...
              </>
            ) : (
              "Save & Use Indicator"
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
